#include "stdafx.h"
#include "./RCryptByte.h"
#include "./RCryptByteArray.h"
#include "./RCryptByteArray2021.h"

#include <strstream>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

namespace NSCRYPT_BYTE
{
	UCHAR ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SIZE][RCRYPT_BYTE_ARRAY_SIZE];
	UCHAR DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SIZE][RCRYPT_BYTE_ARRAY_SIZE];

	BOOL bVALIDARRAY = FALSE;

	void InitArray()
	{
		if ( bVALIDARRAY )	return;

		//clear
		memset(ENCRYPT_ARRAY, 0, sizeof(UCHAR) * (EMRCRYPT_BYTE_TYPE_SIZE * RCRYPT_BYTE_ARRAY_SIZE));
		memset(DECRYPT_ARRAY, 0, sizeof(UCHAR) * (EMRCRYPT_BYTE_TYPE_SIZE * RCRYPT_BYTE_ARRAY_SIZE));

		//copy arrays
		for ( int i=0; i< RCRYPT_BYTE_ARRAY_SIZE; ++i )
		{
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NONE][i]				= CRYPT_BYTE_ARRAY_NONE[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_OLD][i]				= CRYPT_BYTE_ARRAY_OLD[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RAN2][i]				= CRYPT_BYTE_ARRAY_RAN2[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_1][i]			= CRYPT_BYTE_ARRAY_ITEM_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_2][i]			= CRYPT_BYTE_ARRAY_ITEM_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_3][i]			= CRYPT_BYTE_ARRAY_ITEM_VER_3[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_1][i]		= CRYPT_BYTE_ARRAY_SKILL_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_2][i]		= CRYPT_BYTE_ARRAY_SKILL_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_3][i]		= CRYPT_BYTE_ARRAY_SKILL_VER_3[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_1][i]			= CRYPT_BYTE_ARRAY_CROW_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_2][i]			= CRYPT_BYTE_ARRAY_CROW_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_3][i]			= CRYPT_BYTE_ARRAY_CROW_VER_3[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_1][i]		= CRYPT_BYTE_ARRAY_LEVEL_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_2][i]		= CRYPT_BYTE_ARRAY_LEVEL_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_3][i]		= CRYPT_BYTE_ARRAY_LEVEL_VER_3[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_1][i]		= CRYPT_BYTE_ARRAY_NPCTALK_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_2][i]		= CRYPT_BYTE_ARRAY_NPCTALK_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_3][i]		= CRYPT_BYTE_ARRAY_NPCTALK_VER_3[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_QUEST_VER_1][i]		= CRYPT_BYTE_ARRAY_QUEST_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_1][i]	= CRYPT_BYTE_ARRAY_MAPS_LIST_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_2][i]	= CRYPT_BYTE_ARRAY_MAPS_LIST_VER_2[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_MIX_VER_1][i]		= CRYPT_BYTE_ARRAY_ITEMIX[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_TAXI_STATION_VER_1][i] = CRYPT_BYTE_ARRAY_TAXI_STATION_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_1][i]	= CRYPT_BYTE_ARRAY_RANDOM_OPTION_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_2][i]	= CRYPT_BYTE_ARRAY_RANDOM_OPTION_VER_2[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_1][i]		= CRYPT_BYTE_ARRAY_ACTIVITY_FILE_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_2][i]		= CRYPT_BYTE_ARRAY_ACTIVITY_FILE_VER_2[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_BATTLEPASS][i]					= CRYPT_BYTE_ARRAY_BATTLEPASS[i];

			

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_1][i]		= CRYPT_BYTE_ARRAY_SKIN_CONTAINER_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_2][i]		= CRYPT_BYTE_ARRAY_SKIN_CONTAINER_VER_2[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_PIECE_VER_1][i]			= CRYPT_BYTE_ARRAY_SKIN_PIECE_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ANI_CFG_VER_1][i]				= CRYPT_BYTE_ARRAY_ANI_CFG_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ANI_BIN_VER_1][i]				= CRYPT_BYTE_ARRAY_ANI_BIN_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_EFFECT_EGP_VER_1][i]			= CRYPT_BYTE_ARRAY_EFFECT_EGP_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_SHADER_VER_1][i]			= CRYPT_BYTE_ARRAY_MAP_SHADER_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_MATERIAL_VER_1][i]			= CRYPT_BYTE_ARRAY_MAP_MATERIAL_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CLASS_CONST_VER_1][i]			= CRYPT_BYTE_ARRAY_CLASS_CONST_VER_1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_1][i]				= CRYPT_BYTE_ARRAY_WLD1_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_2][i]				= CRYPT_BYTE_ARRAY_WLD1_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_3][i]				= CRYPT_BYTE_ARRAY_WLD1_VER_3[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_4][i]				= CRYPT_BYTE_ARRAY_WLD1_VER_4[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_1][i]				= CRYPT_BYTE_ARRAY_WLD2_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_2][i]				= CRYPT_BYTE_ARRAY_WLD2_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_3][i]				= CRYPT_BYTE_ARRAY_WLD2_VER_3[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_4][i]				= CRYPT_BYTE_ARRAY_WLD2_VER_4[i];
			
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_1][i]				= CRYPT_BYTE_ARRAY_WLD3_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_2][i]				= CRYPT_BYTE_ARRAY_WLD3_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_3][i]				= CRYPT_BYTE_ARRAY_WLD3_VER_3[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_1][i]				= CRYPT_BYTE_ARRAY_MAP_PIE_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_2][i]				= CRYPT_BYTE_ARRAY_MAP_PIE_VER_2[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_3][i]				= CRYPT_BYTE_ARRAY_MAP_PIE_VER_3[i];
			
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LAUNCHER_PATCH_LIST_VER_1][i]	= CRYPT_BYTE_LAUNCHER_PATCH_LIST_VER_1[i];
			
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_1][i]			= CRYPT_BYTE_ARRAY_SERVER_CFG_VER_1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_2][i]			= CRYPT_BYTE_ARRAY_SERVER_CFG_VER_2[i];




			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ITEM_V1][i]				= CRYPT_BYTE_ARRAY_2021_ITEM_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKILL_V1][i]				= CRYPT_BYTE_ARRAY_2021_SKILL_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_CROW_V1][i]				= CRYPT_BYTE_ARRAY_2021_CROW_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_LEVEL_V1][i]				= CRYPT_BYTE_ARRAY_2021_LEVEL_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_NPC_TALK_V1][i]			= CRYPT_BYTE_ARRAY_2021_NPC_TALK_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_MAPS_LIST_V1][i]			= CRYPT_BYTE_ARRAY_2021_MAPS_LIST_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ITEM_MIX_V1][i]			= CRYPT_BYTE_ARRAY_2021_ITEM_MIX_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_TAXI_STATION_V1][i]		= CRYPT_BYTE_ARRAY_2021_TAXI_STATION_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_RANDOM_OPTION_V1][i]		= CRYPT_BYTE_ARRAY_2021_RANDOM_OPTION_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ACTIVITY_V1][i]			= CRYPT_BYTE_ARRAY_2021_ACTIVITY_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_CLASS_CONST_V1][i]		= CRYPT_BYTE_ARRAY_2021_CLASS_CONST_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKIN_PIECE_V1][i]			= CRYPT_BYTE_ARRAY_2021_SKIN_PIECE_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKIN_CHAR_V1][i]			= CRYPT_BYTE_ARRAY_2021_SKIN_CHAR_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_DATA_V1][i]		= CRYPT_BYTE_ARRAY_2021_ATT_BONE_DATA_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_LINK_V1][i]		= CRYPT_BYTE_ARRAY_2021_ATT_BONE_LINK_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_VEHICLE_DATA_V1][i]		= CRYPT_BYTE_ARRAY_2021_VEHICLE_DATA_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_EFFECT_GROUP_V1][i]		= CRYPT_BYTE_ARRAY_2021_EFFECT_GROUP_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ANI_CFG_V1][i]			= CRYPT_BYTE_ARRAY_2021_ANI_CFG_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ANI_BIN_V1][i]			= CRYPT_BYTE_ARRAY_2021_ANI_BIN_V1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD1_V1][i]				= CRYPT_BYTE_ARRAY_2021_WLD1_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD2_V1][i]				= CRYPT_BYTE_ARRAY_2021_WLD2_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD3_V1][i]				= CRYPT_BYTE_ARRAY_2021_WLD3_V1[i];
			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_PIE_V1][i]				= CRYPT_BYTE_ARRAY_2021_PIE_V1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SERVER_CFG_V1][i]			= CRYPT_BYTE_ARRAY_2021_SERVER_CFG_V1[i];

			ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SET_OPTION_V1][i]			= CRYPT_BYTE_ARRAY_2021_SET_OPTION_V1[i];		/* set item option, Juver, 2021/07/31 */
		}

		for (int i = 0; i < RCRYPT_BYTE_ARRAY_SIZE; ++i)
		{
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NONE][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NONE][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_OLD][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_OLD][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RAN2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RAN2][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKILL_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CROW_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LEVEL_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_QUEST_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_QUEST_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_2][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_MIX_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ITEM_MIX_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_TAXI_STATION_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_TAXI_STATION_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_2][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_2][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_BATTLEPASS][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_BATTLEPASS][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_2][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_PIECE_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SKIN_PIECE_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ANI_CFG_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ANI_CFG_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ANI_BIN_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_ANI_BIN_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_EFFECT_EGP_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_EFFECT_EGP_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_SHADER_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_SHADER_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_MATERIAL_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_MATERIAL_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CLASS_CONST_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_CLASS_CONST_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_3][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_4][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_1_VER_4][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_3][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_4][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_2_VER_4][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_WLD_3_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_2][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_3][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_3][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LAUNCHER_PATCH_LIST_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_LAUNCHER_PATCH_LIST_VER_1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_2][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_2][i])] = UCHAR(i);



			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ITEM_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ITEM_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKILL_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKILL_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_CROW_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_CROW_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_LEVEL_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_LEVEL_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_NPC_TALK_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_NPC_TALK_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_MAPS_LIST_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_MAPS_LIST_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ITEM_MIX_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ITEM_MIX_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_TAXI_STATION_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_TAXI_STATION_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_RANDOM_OPTION_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_RANDOM_OPTION_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ACTIVITY_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ACTIVITY_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_CLASS_CONST_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_CLASS_CONST_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKIN_PIECE_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKIN_PIECE_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKIN_CHAR_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SKIN_CHAR_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_DATA_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_DATA_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_LINK_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_LINK_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_VEHICLE_DATA_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_VEHICLE_DATA_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_EFFECT_GROUP_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_EFFECT_GROUP_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ANI_CFG_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ANI_CFG_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ANI_BIN_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_ANI_BIN_V1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD1_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD1_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD2_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD2_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD3_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_WLD3_V1][i])] = UCHAR(i);
			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_PIE_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_PIE_V1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SERVER_CFG_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SERVER_CFG_V1][i])] = UCHAR(i);

			DECRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SET_OPTION_V1][static_cast<DWORD>(ENCRYPT_ARRAY[EMRCRYPT_BYTE_TYPE_2021_SET_OPTION_V1][i])] = UCHAR(i);
		}

#ifdef _DEBUG
		//check if there are duplicates
		for (int nArray = 0; nArray < EMRCRYPT_BYTE_TYPE_SIZE; ++nArray)
		{
			for (int i = 0; i < RCRYPT_BYTE_ARRAY_SIZE; ++i)
			{
				for (int j = 0; j < RCRYPT_BYTE_ARRAY_SIZE; ++j)
				{
					if (i == j)	continue;

					if (DWORD(ENCRYPT_ARRAY[nArray][i]) == DWORD(ENCRYPT_ARRAY[nArray][j]))
						CDebugSet::MsgBox("ENCRYPT_ARRAY %d Duplicate In:%d~%d Value:%x", nArray, i, j, ENCRYPT_ARRAY[nArray][i]);

					if (DWORD(DECRYPT_ARRAY[nArray][i]) == DWORD(DECRYPT_ARRAY[nArray][j]))
						CDebugSet::MsgBox("DECRYPT_ARRAY %d Duplicate In:%d~%d Value:%x", nArray, i, j, DECRYPT_ARRAY[nArray][i]);
				}
			}
		}
#endif // _DEBUG

		

		bVALIDARRAY = TRUE;
	};
	
	/*void byte_encode ( BYTE* pbuffer, DWORD dwSize, EMRCRYPT_BYTE_TYPE emCRYPT )
	{
		if ( !pbuffer )	return;
		if ( emCRYPT == EMRCRYPT_BYTE_TYPE_NONE )		return;
		if ( emCRYPT >= EMRCRYPT_BYTE_TYPE_SIZE )		return;

		InitArray();

		for ( DWORD i=0; i<dwSize; ++i )		
		{
			pbuffer[i] = ENCRYPT_ARRAY[emCRYPT][static_cast<DWORD>(pbuffer[i])];
		}
	}

	void byte_decode ( BYTE* pbuffer, DWORD dwSize, EMRCRYPT_BYTE_TYPE emCRYPT )
	{
		if ( !pbuffer )	return;
		if ( emCRYPT == EMRCRYPT_BYTE_TYPE_NONE )		return;
		if ( emCRYPT >= EMRCRYPT_BYTE_TYPE_SIZE )		return;
	
		InitArray();

		for ( DWORD i=0; i<dwSize; ++i )		
		{
			pbuffer[i] = DECRYPT_ARRAY[emCRYPT][static_cast<DWORD>(pbuffer[i])];
		}
	}*/
}

RCryptByte::RCryptByte()
	: m_emType(EMRCRYPT_BYTE_TYPE_NONE)
{

}

RCryptByte::~RCryptByte()
{

}

bool RCryptByte::Initialize()
{
	if (NSCRYPT_BYTE::bVALIDARRAY == FALSE )
	{
		NSCRYPT_BYTE::InitArray();
	}

	return true;
}

void RCryptByte::SetType(int nType)
{
	m_emType = (EMRCRYPT_BYTE_TYPE)nType;
}

bool RCryptByte::Decrypt(BYTE* pbuffer, DWORD dwSize)
{
	if (!pbuffer)	return false;
	if (m_emType == EMRCRYPT_BYTE_TYPE_NONE)		return false;
	if (m_emType >= EMRCRYPT_BYTE_TYPE_SIZE)		return false;

	Initialize();

	for (DWORD i = 0; i < dwSize; ++i)
	{
		pbuffer[i] = NSCRYPT_BYTE::DECRYPT_ARRAY[m_emType][static_cast<DWORD>(pbuffer[i])];
	}

	return true;
}

bool RCryptByte::Encrypt(BYTE* pbuffer, DWORD dwSize)
{
	if (!pbuffer)	return false;
	if (m_emType == EMRCRYPT_BYTE_TYPE_NONE)		return false;
	if (m_emType >= EMRCRYPT_BYTE_TYPE_SIZE)		return false;

	Initialize();

	for (DWORD i = 0; i < dwSize; ++i)
	{
		pbuffer[i] = NSCRYPT_BYTE::ENCRYPT_ARRAY[m_emType][static_cast<DWORD>(pbuffer[i])];
	}

	return true;
}
