#pragma once

#define RCRYPT_BYTE_ARRAY_SIZE 256


enum EMRCRYPT_BYTE_TYPE
{
	EMRCRYPT_BYTE_TYPE_NONE = 0,
	EMRCRYPT_BYTE_TYPE_OLD,				//orig encryption
	EMRCRYPT_BYTE_TYPE_RAN2,			//used by ran2 files encryption

	EMRCRYPT_BYTE_TYPE_ITEM_VER_1,
	EMRCRYPT_BYTE_TYPE_ITEM_VER_2,
	EMRCRYPT_BYTE_TYPE_ITEM_VER_3,

	EMRCRYPT_BYTE_TYPE_SKILL_VER_1,
	EMRCRYPT_BYTE_TYPE_SKILL_VER_2,
	EMRCRYPT_BYTE_TYPE_SKILL_VER_3,

	EMRCRYPT_BYTE_TYPE_CROW_VER_1,
	EMRCRYPT_BYTE_TYPE_CROW_VER_2,
	EMRCRYPT_BYTE_TYPE_CROW_VER_3,

	EMRCRYPT_BYTE_TYPE_LEVEL_VER_1,
	EMRCRYPT_BYTE_TYPE_LEVEL_VER_2,
	EMRCRYPT_BYTE_TYPE_LEVEL_VER_3,

	EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_1,
	EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_2,
	EMRCRYPT_BYTE_TYPE_NPC_TALK_VER_3,

	EMRCRYPT_BYTE_TYPE_QUEST_VER_1,

	EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_1,
	EMRCRYPT_BYTE_TYPE_MAPS_LIST_VER_2,

	EMRCRYPT_BYTE_TYPE_ITEM_MIX_VER_1,

	EMRCRYPT_BYTE_TYPE_TAXI_STATION_VER_1,

	EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_1,
	EMRCRYPT_BYTE_TYPE_RANDOM_OPTION_FILE_VER_2,

	EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_1,
	EMRCRYPT_BYTE_TYPE_ACTIVITY_FILE_VER_2,

	EMRCRYPT_BYTE_TYPE_BATTLEPASS,

	EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_1,
	EMRCRYPT_BYTE_TYPE_SKIN_CONTAINER_VER_2,

	EMRCRYPT_BYTE_TYPE_SKIN_PIECE_VER_1,

	EMRCRYPT_BYTE_TYPE_ANI_CFG_VER_1,

	EMRCRYPT_BYTE_TYPE_ANI_BIN_VER_1,

	EMRCRYPT_BYTE_TYPE_EFFECT_EGP_VER_1,

	EMRCRYPT_BYTE_TYPE_MAP_SHADER_VER_1,

	EMRCRYPT_BYTE_TYPE_MAP_MATERIAL_VER_1,

	EMRCRYPT_BYTE_TYPE_CLASS_CONST_VER_1,

	EMRCRYPT_BYTE_TYPE_WLD_1_VER_1,
	EMRCRYPT_BYTE_TYPE_WLD_1_VER_2,
	EMRCRYPT_BYTE_TYPE_WLD_1_VER_3,
	EMRCRYPT_BYTE_TYPE_WLD_1_VER_4,

	EMRCRYPT_BYTE_TYPE_WLD_2_VER_1,
	EMRCRYPT_BYTE_TYPE_WLD_2_VER_2,
	EMRCRYPT_BYTE_TYPE_WLD_2_VER_3,
	EMRCRYPT_BYTE_TYPE_WLD_2_VER_4,

	EMRCRYPT_BYTE_TYPE_WLD_3_VER_1,
	EMRCRYPT_BYTE_TYPE_WLD_3_VER_2,
	EMRCRYPT_BYTE_TYPE_WLD_3_VER_3,

	EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_1,
	EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_2,
	EMRCRYPT_BYTE_TYPE_MAP_PIE_VER_3,

	EMRCRYPT_BYTE_TYPE_LAUNCHER_PATCH_LIST_VER_1,

	EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_1,
	EMRCRYPT_BYTE_TYPE_SERVER_CFG_VER_2,


	EMRCRYPT_BYTE_TYPE_2021_ITEM_V1,
	EMRCRYPT_BYTE_TYPE_2021_SKILL_V1,
	EMRCRYPT_BYTE_TYPE_2021_CROW_V1,
	EMRCRYPT_BYTE_TYPE_2021_LEVEL_V1,
	EMRCRYPT_BYTE_TYPE_2021_NPC_TALK_V1,
	EMRCRYPT_BYTE_TYPE_2021_MAPS_LIST_V1,
	EMRCRYPT_BYTE_TYPE_2021_ITEM_MIX_V1,
	EMRCRYPT_BYTE_TYPE_2021_TAXI_STATION_V1,
	EMRCRYPT_BYTE_TYPE_2021_RANDOM_OPTION_V1,
	EMRCRYPT_BYTE_TYPE_2021_ACTIVITY_V1,
	EMRCRYPT_BYTE_TYPE_2021_CLASS_CONST_V1,
	EMRCRYPT_BYTE_TYPE_2021_SKIN_PIECE_V1,
	EMRCRYPT_BYTE_TYPE_2021_SKIN_CHAR_V1,
	EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_DATA_V1,
	EMRCRYPT_BYTE_TYPE_2021_ATT_BONE_LINK_V1,
	EMRCRYPT_BYTE_TYPE_2021_VEHICLE_DATA_V1,
	EMRCRYPT_BYTE_TYPE_2021_EFFECT_GROUP_V1,
	EMRCRYPT_BYTE_TYPE_2021_ANI_CFG_V1,
	EMRCRYPT_BYTE_TYPE_2021_ANI_BIN_V1,
	EMRCRYPT_BYTE_TYPE_2021_WLD1_V1,
	EMRCRYPT_BYTE_TYPE_2021_WLD2_V1,
	EMRCRYPT_BYTE_TYPE_2021_WLD3_V1,
	EMRCRYPT_BYTE_TYPE_2021_PIE_V1,

	EMRCRYPT_BYTE_TYPE_2021_SERVER_CFG_V1,

	EMRCRYPT_BYTE_TYPE_2021_SET_OPTION_V1,		/* set item option, Juver, 2021/07/31 */

	EMRCRYPT_BYTE_TYPE_SIZE,
};
