#ifndef APPSTRING_H__INCLUDED
#define APPSTRING_H__INCLUDED

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

enum EMAPP_STRING
{
	EMAPP_STRING_BASE = 0,
	EMAPP_STRING_LAUNCH_FAILED,
	EMAPP_STRING_DIRECTX_OLD,
	EMAPP_STRING_CLASS_REG_FAILED,
	EMAPP_STRING_RCC_PARAMETER_1,
	EMAPP_STRING_RCC_PARAMETER_2,
	EMAPP_STRING_SIZE,
};

namespace NSAPP_STRING
{
	const TCHAR* getc( EMAPP_STRING emType );
	std::string gets( EMAPP_STRING emType );

	extern std::string strInfo[EMAPP_STRING_SIZE];
};

#endif // APPSTRING_H__INCLUDED
