//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ServerSetting.rc
//
#define IDD_EDITOR_SHADER_DIALOG        102
#define IDD_SERVER_SETUP_DIALOG         102
#define IDD_SERVER_SETTING_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_PAGE_BASIC                  313
#define IDD_PAGE_DATABASE               314
#define IDD_PAGE_SERVER_1               315
#define IDD_PAGE_SERVER_2               316
#define IDC_LIST_FIELD_SERVER           1016
#define IDC_BTN_LOAD                    1017
#define IDC_BTN_SAVE                    1018
#define IDC_BTN_IMPORT                  1019
#define IDC_EDIT_FILENAME               1020
#define IDC_STATIC_TOOL                 1021
#define IDC_CHECK_PKLESS                1023
#define IDC_CHECK_PK                    1024
#define IDC_CHECK_ADULT                 1025
#define IDC_CHECK_USE_EVENT_THREAD      1026
#define IDC_CHECK_TEST_SERVER           1027
#define IDC_CHECK_HEARTBEAT             1028
#define IDC_CHECK_GAME_GUARD_AUTH       1029
#define IDC_EDIT_SERVER_VERSION         1030
#define IDC_EDIT_PATCH_VERSION          1031
#define IDC_EDIT_SERVER_NAME            1032
#define IDC_EDIT_SERVER_MAX_CLIENT      1033
#define IDC_EDIT_SERVER_MAX_CHANNEL_CLIENT 1034
#define IDC_EDIT_SERVER_IP              1035
#define IDC_EDIT_SERVER_SERVICE_PORT    1036
#define IDC_EDIT_SERVER_CONTROL_PORT    1037
#define IDC_EDIT_SERVER_TYPE            1038
#define IDC_EDIT_SERVER_GROUP           1039
#define IDC_EDIT_SERVER_FIELD           1040
#define IDC_EDIT_USER_ODBC_SERVER       1040
#define IDC_EDIT_SERVER_CHANNEL         1041
#define IDC_EDIT_USER_ODBC_USER         1041
#define IDC_EDIT_AGENT_IP               1041
#define IDC_EDIT_SERVER_CHANNEL_NUMBER  1042
#define IDC_EDIT_USER_ODBC_PASS         1042
#define IDC_EDIT_SESSION_NAME           1042
#define IDC_EDIT_SERVICE_PROVIDER       1043
#define IDC_EDIT_USER_ODBC_DATABASE     1043
#define IDC_EDIT_SESSION_IP             1043
#define IDC_EDIT_MAX_THREAD             1044
#define IDC_EDIT_USER_ODBC_POOL_SIZE    1044
#define IDC_EDIT_SESSION_PORT           1044
#define IDC_EDIT_LANGUAGE_SET           1045
#define IDC_EDIT_USER_ODBC_RESPONSE_TIME 1045
#define IDC_EDIT_SESSION_USER           1045
#define IDC_EDIT_WHITE_ROCK_SERVER      1046
#define IDC_EDIT_GAME_ODBC_SERVER       1046
#define IDC_EDIT_SESSION_PASS           1046
#define IDC_EDIT_WHITE_ROCK_PORT        1047
#define IDC_EDIT_GAME_ODBC_USER         1047
#define IDC_EDIT_LOGIN_NAME             1047
#define IDC_EDIT_IP_CLIENT_MAX          1048
#define IDC_EDIT_GAME_ODBC_PASS         1048
#define IDC_EDIT_LOGIN_IP               1048
#define IDC_EDIT_GAME_ODBC_DATABASE     1049
#define IDC_EDIT_LOGIN_PORT             1049
#define IDC_EDIT_SERVER_NUMBER          1049
#define IDC_EDIT_GAME_ODBC_POOL_SIZE    1050
#define IDC_EDIT_LOGIN_USER             1050
#define IDC_EDIT_HASH_CPU               1050
#define IDC_EDIT_GAME_ODBC_RESPONSE_TIME 1051
#define IDC_EDIT_LOGIN_PASS             1051
#define IDC_EDIT_HASH_LAN               1051
#define IDC_EDIT_LOG_ODBC_SERVER        1052
#define IDC_CHECK_CHANNEL_PK_0          1052
#define IDC_EDIT_HASH_DISK              1052
#define IDC_EDIT_LOG_ODBC_USER          1053
#define IDC_CHECK_CHANNEL_PK_1          1053
#define IDC_EDIT_HASH_NAME              1053
#define IDC_EDIT_LOG_ODBC_PASS          1054
#define IDC_CHECK_CHANNEL_PK_2          1054
#define IDC_EDIT_SERVER_NOTE            1054
#define IDC_EDIT_LOG_ODBC_DATABASE      1055
#define IDC_CHECK_CHANNEL_PK_3          1055
#define IDC_EDIT_HASH_NAME2             1055
#define IDC_EDIT_HASH_ALL               1055
#define IDC_EDIT_LOG_ODBC_POOL_SIZE     1056
#define IDC_CHECK_CHANNEL_PK_4          1056
#define IDC_EDIT_SERVER_IP2             1056
#define IDC_EDIT_SERVER_IP_PROXY        1056
#define IDC_EDIT_LOG_ODBC_RESPONSE_TIME 1057
#define IDC_CHECK_CHANNEL_PK_5          1057
#define IDC_EDIT_SERVER_IP3             1057
#define IDC_EDIT_SERVER_SERVICEPORT_LIST 1057
#define IDC_EDIT_SHOP_ODBC_SERVER       1058
#define IDC_CHECK_CHANNEL_PK_6          1058
#define IDC_EDIT_SHOP_ODBC_USER         1059
#define IDC_CHECK_CHANNEL_PK_7          1059
#define IDC_EDIT_SHOP_ODBC_PASS         1060
#define IDC_CHECK_CHANNEL_PK_8          1060
#define IDC_EDIT_SHOP_ODBC_DATABASE     1061
#define IDC_CHECK_CHANNEL_PK_9          1061
#define IDC_EDIT_SHOP_ODBC_POOL_SIZE    1062
#define IDC_EDIT_FIELD_NAME             1062
#define IDC_EDIT_SHOP_ODBC_RESPONSE_TIME 1063
#define IDC_EDIT_FIELD_IP               1063
#define IDC_EDIT_TERRA_ODBC_SERVER      1064
#define IDC_EDIT_FIELD_PORT             1064
#define IDC_EDIT_TERRA_ODBC_USER        1065
#define IDC_EDIT_FIELD_CHANNEL          1065
#define IDC_EDIT_TERRA_ODBC_PASS        1066
#define IDC_EDIT_FIELD_ID               1066
#define IDC_EDIT_TERRA_ODBC_DATABASE    1067
#define IDC_BUTTON_FIELD_SAVE           1067
#define IDC_EDIT_TERRA_ODBC_POOL_SIZE   1068
#define IDC_BUTTON_BASIC_SAVE           1068
#define IDC_BUTTON_FIELD_CANCEL         1068
#define IDC_EDIT_TERRA_ODBC_RESPONSE_TIME 1069
#define IDC_EDIT_FIELD_IP2              1069
#define IDC_EDIT_GSP_ODBC_SERVER        1070
#define IDC_EDIT_GSP_ODBC_USER          1071
#define IDC_EDIT_GSP_ODBC_PASS          1072
#define IDC_EDIT_GSP_ODBC_DATABASE      1073
#define IDC_EDIT_GSP_ODBC_POOL_SIZE     1074
#define IDC_EDIT_GSP_ODBC_RESPONSE_TIME 1075
#define IDC_EDIT_KOR_ODBC_SERVER        1076
#define IDC_EDIT_KOR_ODBC_USER          1077
#define IDC_EDIT_KOR_ODBC_PASS          1078
#define IDC_EDIT_KOR_ODBC_DATABASE      1079
#define IDC_EDIT_KOR_ODBC_POOL_SIZE     1080
#define IDC_EDIT_KOR_ODBC_RESPONSE_TIME 1081
#define IDC_EDIT_MY_ODBC_SERVER         1082
#define IDC_EDIT_MY_ODBC_USER           1083
#define IDC_EDIT_MY_ODBC_PASS           1084
#define IDC_EDIT_MY_ODBC_DATABASE       1085
#define IDC_EDIT_MY_ODBC_POOL_SIZE      1086
#define IDC_EDIT_MY_ODBC_RESPONSE_TIME  1087
#define IDC_BUTTON_DATABASE_SAVE        1088
#define IDC_BUTTON_SERVER_1_SAVE        1089
#define IDC_EDIT_FIELD_SERVER_MAX_ID    1090
#define IDC_BUTTON1                     1091
#define IDC_BUTTON_SERVER_2_FIELD_EDIT  1091
#define IDC_BUTTON_HASH_BUILD           1091
#define IDC_CHECK_USE_PROXY             1092

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
