/*!
 * \file s_NetMsgEnum.h
 *
 * \author Juver
 * \date 2020/11/05
 *
 * 
 */

#ifndef S_NETMSGENUM_H_INCLUDED__
#define S_NETMSGENUM_H_INCLUDED__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

/*register page, Juver, 2017/11/18 */
enum EMREGISTER_FB
{
	EMREGISTER_FB_ERROR_SERVER				= 0,
	EMREGISTER_FB_ERROR_NOTREG				= 1,
	EMREGISTER_FB_ERROR_ONREGWAIT			= 2,
	EMREGISTER_FB_GOOD_WAITING				= 3,
	EMREGISTER_FB_GOOD_ERROR				= 4,
	EMREGISTER_FB_GOOD_TAKEN				= 5,
	EMREGISTER_FB_GOOD_DONE					= 6,
	EMREGISTER_FB_GOOD_MAIL_TAKEN			= 7,

	EMREGISTER_FB_ERROR_LESS_USERID			= 8,
	EMREGISTER_FB_ERROR_LESS_PASS1			= 9,
	EMREGISTER_FB_ERROR_LESS_PASS2			= 10,
	EMREGISTER_FB_ERROR_LESS_MAIL			= 11,
	EMREGISTER_FB_ERROR_LESS_SA				= 12,
	EMREGISTER_FB_ERROR_MAX_USERID			= 13,
	EMREGISTER_FB_ERROR_MAX_PASS1			= 14,
	EMREGISTER_FB_ERROR_MAX_PASS2			= 15,
	EMREGISTER_FB_ERROR_MAX_MAIL			= 16,
	EMREGISTER_FB_ERROR_MAX_SA				= 17,
	EMREGISTER_FB_ERROR_INVALID_USERID		= 18,
	EMREGISTER_FB_ERROR_INVALID_PASS1		= 19,
	EMREGISTER_FB_ERROR_INVALID_PASS2		= 20,
	EMREGISTER_FB_ERROR_INVALID_MAIL		= 21,
	EMREGISTER_FB_ERROR_INVALID_SA			= 22,

	EMREGISTER_FB_ERROR_LESS_FULLNAME		= 23,
	EMREGISTER_FB_ERROR_MAX_FULLNAME		= 24,
	EMREGISTER_FB_ERROR_INVALID_FULLNAME	= 25,

	//PCID
	EMREGISTER_FB_ERROR_BLOCK_PCID			= 26,

	EMREGISTER_FB_ERROR_LESS_REFERRAL		= 27,
	EMREGISTER_FB_ERROR_MAX_REFERRAL		= 28,
	EMREGISTER_FB_ERROR_INVALID_REFERRAL	= 29,

	EMREGISTER_FB_ERROR_INVALID_REFERRAL2	= 30,
};

/*register page, Juver, 2017/11/18 */
enum EMREGISTER_FB2
{
	EMREGISTER_FB2_OK			= 0,
	EMREGISTER_FB2_USER_USED	= 1,
	EMREGISTER_FB2_EMAIL_USED	= 2,
	EMREGISTER_FB2_ERROR		= 3,

	//PCID
	EMREGISTER_FB2_PCID_BLOCKED	= 4,	

	EMREGISTER_FB2_REFERRAL_INVALID	= 5,	
};

/* login device check, Juver, 2020/11/06 */
enum EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB
{
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_ERROR_SERVER		= 0,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_PASS_EMPTY		= 1,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_PASS_SIZE			= 2,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_PASS_STRING		= 3,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_ALREADY_ENABLED	= 4,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_ALREADY_DISABLED	= 5,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_GOOD_WAIT			= 6,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_GOOD_ERROR		= 7,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_GOOD_DONE			= 8,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_GOOD_NOT_FOUND	= 9,
};

/* login device check, Juver, 2020/11/06 */
enum EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB2
{
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_ERROR			= 0,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_DONE			= 1,
	EMUSER_ACCOUNT_PAGE_LOGIN_DEVICE_CHECK_SET_FB_NOT_FOUND		= 2,	
};


/* login device check, Juver, 2020/11/07 */
enum EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB
{
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_SERVER				= 0,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_NOT_INIT			= 1,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_ON_WAIT			= 2,

	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_LEN_USERID			= 3,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_LEN_PASS			= 4,

	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_INVALID_USERID		= 5,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_INVALID_PASS		= 6,

	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_ERROR_LEN_PCID			= 7,

	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_GOOD_WAITING				= 8,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_GOOD_ERROR				= 9,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_GOOD_SUCCESS				= 10,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB_GOOD_INCORRECT_PASS		= 11,
};

/* login device check, Juver, 2020/11/07 */
enum EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB2
{
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB2_ERROR					= 0,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB2_SUCCESS					= 1,
	EMUSER_LOGIN_DEVICE_CHECK_VERIFY_REQUEST_ACTION_FB2_PASS_INCORRECT			= 2,
};

#endif // S_NETMSGENUM_H_INCLUDED__


