#include "StdAfx.h"
#include "./BasicLineBoxEx.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

CBasicLineBoxEx::CBasicLineBoxEx ()
{
}

CBasicLineBoxEx::~CBasicLineBoxEx ()
{
}

void CBasicLineBoxEx::CreateBaseBoxStorageCard ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_STORAGE_CARD" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_STORAGE_CARD", "BASIC_LINE_BOX_EX_RIGHT_STORAGE_CARD", "BASIC_LINE_BOX_EX_TOP_STORAGE_CARD", "BASIC_LINE_BOX_EX_BOTTOM_STORAGE_CARD" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_STORAGE_CARD", "BASIC_LINE_BOX_EX_LEFTBOTTOM_STORAGE_CARD", "BASIC_LINE_BOX_EX_RIGHTTOP_STORAGE_CARD", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_STORAGE_CARD" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateBaseBoxESCMenu ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_ESC" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_ESC", "BASIC_LINE_BOX_EX_RIGHT_ESC", "BASIC_LINE_BOX_EX_TOP_ESC", "BASIC_LINE_BOX_EX_BOTTOM_ESC" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_ESC", "BASIC_LINE_BOX_EX_LEFTBOTTOM_ESC", "BASIC_LINE_BOX_EX_RIGHTTOP_ESC", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_ESC" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateBaseBoxVarTextBox ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_VARTEXT" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_VARTEXT", "BASIC_LINE_BOX_EX_RIGHT_VARTEXT", "BASIC_LINE_BOX_EX_TOP_VARTEXT", "BASIC_LINE_BOX_EX_BOTTOM_VARTEXT" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_VARTEXT", "BASIC_LINE_BOX_EX_LEFTBOTTOM_VARTEXT", "BASIC_LINE_BOX_EX_RIGHTTOP_VARTEXT", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_VARTEXT" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateBaseBoxVarTextBoxEx(char* szBoxControl)
{
	CreateBodyImage("BASIC_LINE_BOX_EX_BODY_VARTEXT_EX");
	CreateLineImage("BASIC_LINE_BOX_EX_LEFT_VARTEXT_EX", "BASIC_LINE_BOX_EX_RIGHT_VARTEXT_EX", "BASIC_LINE_BOX_EX_TOP_VARTEXT_EX", "BASIC_LINE_BOX_EX_BOTTOM_VARTEXT_EX");
	CreateLineImageEx("BASIC_LINE_BOX_EX_LEFTTOP_VARTEXT_EX", "BASIC_LINE_BOX_EX_LEFTBOTTOM_VARTEXT_EX", "BASIC_LINE_BOX_EX_RIGHTTOP_VARTEXT_EX", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_VARTEXT_EX");
	ResizeControl(szBoxControl);
}

void CBasicLineBoxEx::CreateBaseBoxTargetInfo ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_TARGETINFO" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_TARGETINFO", "BASIC_LINE_BOX_EX_RIGHT_TARGETINFO", "BASIC_LINE_BOX_EX_TOP_TARGETINFO", "BASIC_LINE_BOX_EX_BOTTOM_TARGETINFO" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_TARGETINFO", "BASIC_LINE_BOX_EX_LEFTBOTTOM_TARGETINFO", "BASIC_LINE_BOX_EX_RIGHTTOP_TARGETINFO", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_TARGETINFO" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxSimpleHP ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_SIMPLEHP" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_SIMPLEHP", "BASIC_LINE_BOX_EX_RIGHT_SIMPLEHP", "BASIC_LINE_BOX_EX_TOP_SIMPLEHP", "BASIC_LINE_BOX_EX_BOTTOM_SIMPLEHP" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_SIMPLEHP", "BASIC_LINE_BOX_EX_LEFTBOTTOM_SIMPLEHP", "BASIC_LINE_BOX_EX_RIGHTTOP_SIMPLEHP", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_SIMPLEHP" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateBaseBoxName ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_NAME" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_NAME", "BASIC_LINE_BOX_EX_RIGHT_NAME", "BASIC_LINE_BOX_EX_TOP_NAME", "BASIC_LINE_BOX_EX_BOTTOM_NAME" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_NAME", "BASIC_LINE_BOX_EX_LEFTBOTTOM_NAME", "BASIC_LINE_BOX_EX_RIGHTTOP_NAME", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_NAME" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateBaseBoxNameCD ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_NAME_CD" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_NAME", "BASIC_LINE_BOX_EX_RIGHT_NAME", "BASIC_LINE_BOX_EX_TOP_NAME", "BASIC_LINE_BOX_EX_BOTTOM_NAME" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_NAME", "BASIC_LINE_BOX_EX_LEFTBOTTOM_NAME", "BASIC_LINE_BOX_EX_RIGHTTOP_NAME", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_NAME" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateBaseBoxChat ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_EX_BODY_CHAT" );
	CreateLineImage ( "BASIC_LINE_BOX_EX_LEFT_CHAT", "BASIC_LINE_BOX_EX_RIGHT_CHAT", "BASIC_LINE_BOX_EX_TOP_CHAT", "BASIC_LINE_BOX_EX_BOTTOM_CHAT" );
	CreateLineImageEx ( "BASIC_LINE_BOX_EX_LEFTTOP_CHAT", "BASIC_LINE_BOX_EX_LEFTBOTTOM_CHAT", "BASIC_LINE_BOX_EX_RIGHTTOP_CHAT", "BASIC_LINE_BOX_EX_RIGHTBOTTOM_CHAT" );
	ResizeControl ( szBoxControl );	
}

void CBasicLineBoxEx::CreateLineImageEx ( char* szLeftTop, char* szLeftBottom, char* szRightTop, char* szRIghtBottom )
{
	m_pLeftTop = CreateControl ( szLeftTop, UI_FLAG_DEFAULT );
	m_pLeftBottom = CreateControl ( szLeftBottom, UI_FLAG_BOTTOM );
	m_pRIghtTop = CreateControl ( szRightTop, UI_FLAG_RIGHT );
	m_pRightBottom = CreateControl ( szRIghtBottom, UI_FLAG_BOTTOM | UI_FLAG_RIGHT );
}

void	CBasicLineBoxEx::CreateBaseBoxCompetitionNotify ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_COMPETITION_NOTIFY_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_COMPETITION_NOTIFY_LEFT", "BASIC_LINE_BOX_COMPETITION_NOTIFY_RIGHT", "BASIC_LINE_BOX_COMPETITION_NOTIFY_TOP", "BASIC_LINE_BOX_COMPETITION_NOTIFY_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_COMPETITION_NOTIFY_LEFTTOP", "BASIC_LINE_BOX_COMPETITION_NOTIFY_LEFTBOTTOM", "BASIC_LINE_BOX_COMPETITION_NOTIFY_RIGHTTOP", "BASIC_LINE_BOX_COMPETITION_NOTIFY_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxCompetitionNotice ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_COMPETITION_NOTICE_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_COMPETITION_NOTICE_LEFT", "BASIC_LINE_BOX_COMPETITION_NOTICE_RIGHT", "BASIC_LINE_BOX_COMPETITION_NOTICE_TOP", "BASIC_LINE_BOX_COMPETITION_NOTICE_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_COMPETITION_NOTICE_LEFTTOP", "BASIC_LINE_BOX_COMPETITION_NOTICE_LEFTBOTTOM", "BASIC_LINE_BOX_COMPETITION_NOTICE_RIGHTTOP", "BASIC_LINE_BOX_COMPETITION_NOTICE_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxCompetitionWindow ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_COMPETITION_WINDOW_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_COMPETITION_WINDOW_LEFT", "BASIC_LINE_BOX_COMPETITION_WINDOW_RIGHT", "BASIC_LINE_BOX_COMPETITION_WINDOW_TOP", "BASIC_LINE_BOX_COMPETITION_WINDOW_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_COMPETITION_WINDOW_LEFTTOP", "BASIC_LINE_BOX_COMPETITION_WINDOW_LEFTBOTTOM", "BASIC_LINE_BOX_COMPETITION_WINDOW_RIGHTTOP", "BASIC_LINE_BOX_COMPETITION_WINDOW_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxModernSkillYellow ( char* szBoxControl )
{
	CreateBodyImage ( "RAN_BASIC_LINE_BOX_BODY_Y" );
	CreateLineImage ( "RAN_BASIC_LINE_BOX_LEFT_Y", "RAN_BASIC_LINE_BOX_RIGHT_Y", "RAN_BASIC_LINE_BOX_TOP_Y", "RAN_BASIC_LINE_BOX_BOTTOM_Y" );
	CreateLineImageEx ( "RAN_BASIC_LINE_BOX_LEFT_TOP_Y", "RAN_BASIC_LINE_BOX_LEFT_BOTTOM_Y", "RAN_BASIC_LINE_BOX_RIGHT_TOP_Y", "RAN_BASIC_LINE_BOX_RIGHT_BOTTOM_Y" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxModernSkillGreen ( char* szBoxControl )
{
	CreateBodyImage ( "RAN_BASIC_LINE_BOX_BODY_G" );
	CreateLineImage ( "RAN_BASIC_LINE_BOX_LEFT_G", "RAN_BASIC_LINE_BOX_RIGHT_G", "RAN_BASIC_LINE_BOX_TOP_G", "RAN_BASIC_LINE_BOX_BOTTOM_G" );
	CreateLineImageEx ( "RAN_BASIC_LINE_BOX_LEFT_TOP_G", "RAN_BASIC_LINE_BOX_LEFT_BOTTOM_G", "RAN_BASIC_LINE_BOX_RIGHT_TOP_G", "RAN_BASIC_LINE_BOX_RIGHT_BOTTOM_G" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxModernSkillBlue ( char* szBoxControl )
{
	CreateBodyImage ( "RAN_BASIC_LINE_BOX_BODY_B" );
	CreateLineImage ( "RAN_BASIC_LINE_BOX_LEFT_B", "RAN_BASIC_LINE_BOX_RIGHT_B", "RAN_BASIC_LINE_BOX_TOP_B", "RAN_BASIC_LINE_BOX_BOTTOM_B" );
	CreateLineImageEx ( "RAN_BASIC_LINE_BOX_LEFT_TOP_B", "RAN_BASIC_LINE_BOX_LEFT_BOTTOM_B", "RAN_BASIC_LINE_BOX_RIGHT_TOP_B", "RAN_BASIC_LINE_BOX_RIGHT_BOTTOM_B" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxPartyInfoLineBox ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_PARTY_INFO_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_PARTY_INFO_LEFT", "BASIC_LINE_BOX_PARTY_INFO_RIGHT", "BASIC_LINE_BOX_PARTY_INFO_TOP", "BASIC_LINE_BOX_PARTY_INFO_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_PARTY_INFO_LEFTTOP", "BASIC_LINE_BOX_PARTY_INFO_LEFTBOTTOM", "BASIC_LINE_BOX_PARTY_INFO_RIGHTTOP", "BASIC_LINE_BOX_PARTY_INFO_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxPartyInfoSelectBox ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_LEFT", "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_RIGHT", "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_TOP", "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_LEFTTOP", "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_LEFTBOTTOM", "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_RIGHTTOP", "BASIC_LINE_BOX_PARTY_INFO_SELECTBOX_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxCDMProgressBG ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_RNCDMPROGRESS_BG_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_RNCDMPROGRESS_BG_LEFT", "BASIC_LINE_BOX_RNCDMPROGRESS_BG_RIGHT", "BASIC_LINE_BOX_RNCDMPROGRESS_BG_TOP", "BASIC_LINE_BOX_RNCDMPROGRESS_BG_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_RNCDMPROGRESS_BG_LEFTTOP", "BASIC_LINE_BOX_RNCDMPROGRESS_BG_LEFTBOTTOM", "BASIC_LINE_BOX_RNCDMPROGRESS_BG_RIGHTTOP", "BASIC_LINE_BOX_RNCDMPROGRESS_BG_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}

void	CBasicLineBoxEx::CreateBaseBoxCTFResultRankingLineBox ( char* szBoxControl )
{
	CreateBodyImage ( "BASIC_LINE_BOX_CTF_RESULT_RANKING_BODY" );
	CreateLineImage ( "BASIC_LINE_BOX_CTF_RESULT_RANKING_LEFT", "BASIC_LINE_BOX_CTF_RESULT_RANKING_RIGHT", "BASIC_LINE_BOX_CTF_RESULT_RANKING_TOP", "BASIC_LINE_BOX_CTF_RESULT_RANKING_BOTTOM" );
	CreateLineImageEx ( "BASIC_LINE_BOX_CTF_RESULT_RANKING_LEFTTOP", "BASIC_LINE_BOX_CTF_RESULT_RANKING_LEFTBOTTOM", "BASIC_LINE_BOX_CTF_RESULT_RANKING_RIGHTTOP", "BASIC_LINE_BOX_CTF_RESULT_RANKING_RIGHTBOTTOM" );
	ResizeControl ( szBoxControl );	
}