#pragma	once

#include "../Lib_Engine/GUInterface/UIDataType.h"

enum
{
	MODAL_CLOSEGAME = NO_ID + 1,
	MODAL_TEST_MODAL,
	MODAL_INVENTORY_MONEY_TO_FIELD,   
	MODAL_PARTY_TAR,
	MODAL_PARTY_REQ,

	/*charinfoview , Juver, 2017/11/11 */
	MODAL_PARTY_REQ_VIEW_CHAR_INFO,

	/* modern friend window, Juver, 2020/03/02 */
	MODAL_PARTY_REQ_PARTY_WINDOW,	

	/* party charid/charname, Juver, 2020/03/02 */
	MODAL_PARTY_REQ_GUILD_WINDOW,

	MODAL_TRADE_REQ,
	MODAL_REBIRTH,
	//MODAL_DROPMONEY,
	MODAL_TRADEMONEY,
	MODAL_SAVEMONEY,
	MODAL_CLUB_SAVEMONEY,
	MODAL_LOADMONEY,	
    MODAL_CLUB_LOADMONEY,
	MODAL_SPLIT_ITEM,
	MODAL_STORAGE_SPLIT_ITEM,
	MODAL_CLUB_STORAGE_SPLIT_ITEM,
	MODAL_CONFLICT_ONE_TAR,
	MODAL_CONFLICT_PARTY_TAR,
	MODAL_CONFLICT_GUILD_TAR,
	MODAL_CONFLICT_ONE_REQ,	
	MODAL_CONFLICT_PARTY_REQ,
	MODAL_CONFLICT_GUILD_REQ,
	MODAL_PILE_ITEM,
	MODAL_SERVER_STAGE,
	MODAL_BUY_ITEM,
	MODAL_SELL_ITEM,
	MODAL_QUEST_GIVEUP,
	MODAL_FRIEND_ADD,
	MODAL_FRIEND_DEL,
	MODAL_FRIEND_MOVE,
	MODAL_ADD_FRIEND_LURE_ANS,
	MODAL_DEFAULT_POS,
	MODAL_LOTTO,
	MODAL_STORAGE_CHARGE,
	MODAL_PRIVATE_MARKET_SELL,
	MODAL_PRIVATE_MARKET_BUY,
	MODAL_PRIVATE_MARKET_PILE,
	MODAL_PRIVATE_MARKET_QUIT,
	MODAL_CLUB_KICK,
	MODAL_CLUB_BREAKUP,
	MODAL_CLUB_CHANGE_MARK,
	MODAL_CLUB_NICK,
	MODAL_CLUB_JOIN_ASK,
	MODAL_CLUB_JOIN,
	MODAL_CLUB_BREAKUP_CANCEL,
	MODAL_CLUB_SELFQUIT,
	MODAL_CLUB_AUTHORITY,
	MODAL_CLUB_AUTHORITY_ASK,
	CLUB_AUTHORITY_MEMBER_ASK,
	MODAL_SKILL_LEVEL_UP_CONFIRM,
	MODAL_COMMISSION,
	MODAL_FRIEND_BLOCK_ADD_N,
	MODAL_FRIEND_BLOCK_ADD_B,
	MODAL_FRIEND_BLOCK_DEL,
	MODAL_UNION_JOIN_ASK,
	MODAL_UNION_JOIN,
	MODAL_UNION_KICK,
	MODAL_UNION_LEAVE,
	MODAL_UNION_BREAKUP,
	MODAL_CHAR_RENAME,
	MODAL_PET_RENAME,
	MODAL_ITEMREBUILD_MONEY,
	MODAL_ITEMREBUILD_OKQUESTION,
	MODAL_HAIRCOLOR_INFO,
	MODAL_PETCOLOR_INFO,
	MODAL_MOBILE_NUMBER,
	MODAL_KEYSETTING_ERROR,
	MODAL_RESET_SKILLSTATS,
	MODAL_ADD_CONTRIBUTION, // Contribution Item - JX
	MODAL_GENDER_CHANGE,
	MODAL_GENDER_CHANGE_END,
	MODAL_ITEMGARBAGE_OKQUESTION,
	MODAL_RECOVERY_EXP,
	MODAL_RECOVERY_NPC_EXP,
	MODAL_CLUB_BATTLE_ASK,
	MODAL_CLUB_BATTLE_ARMISTICE,
	MODAL_CLUB_BATTLE_ARMISTICE_ASK,
	MODAL_CLUB_BATTLE_SUBMISSION,
	MODAL_ALLIANCE_BATTLE_ASK,
	MODAL_ALLIANCE_BATTLE_ARMISTICE,
	MODAL_ALLIANCE_BATTLE_ARMISTICE_ASK,
	MODAL_ALLIANCE_BATTLE_SUBMISSION,
	MODAL_ITEMMIX_OKQUESTION,

	/*npc shop, Juver, 2017/07/27 */
	MODAL_NPCSHOP_PURCHASE,		

	/*product item, Juver, 2017/10/17 */
	MODAL_ITEM_PRODUCT_PRODUCE,

	/*item wrapper, Juver, 2018/01/12 */
	MODAL_WRAP_ITEM,
	MODAL_UNWRAP_ITEM,
	
	/* Add ItemShop, Ssodomain, 11-09-2023, Start */
	MODAL_BUYITEM,
	/* Add ItemShop, Ssodomain, 11-09-2023, End */

	/*modern inventory window, Juver, 2018/04/09 */
	MODAL_MODERN_INVENTORY_LOCKER,
	MODAL_MODERN_INVENTORY_BACKPACK,
	MODAL_MODERN_INVENTORY_WASTEBASKET,
	MODAL_MODERN_INVENTORY_SORT,

	/*buffs manual remove, Juver, 2018/08/13 */
	MODAL_BUFF_MANUAL_REMOVE,

	/*item drop question, Juver, 2018/08/22 */
	MODAL_INVEN_ITEM_DROP,

	/*item bank question, Juver, 2018/08/22 */
	MODAL_ITEM_BANK_RETRIEVE,

	/*manual lunchbox remove, Juver, 2018/09/19 */
	MODAL_LUNCHBOX_MANUAL_REMOVE,

	/*item random option rebuild, Juver, 2018/07/04 */
	ITEM_RANDOM_OPTION_REBUILD_START_QUESTION,

	PET_CARD_SUMMON_QUESTION,
	PET_CARD_DISMISS_QUESTION,

	/* party finder, Juver, 2020/01/16 */
	MODAL_PARTY_FINDER_JOIN_QUESTION,

	MODAL_NPC_CONTRIBUTION_SHOP_PURCHASE,

	MODAL_SKILL_PURCHASE_CONFIRM,
	/* Gacha System, MontageDev 7/10/24 */
	MODAL_OPEN_GACHA,
	
	MODAL_REGISTER_CODEX, /* Codex, Archie 02/16/24 */

	MODAL_RESET_STATS, /* Reset Stats Item */
};