/*!
 * \file OuterInterfaceGuid.h
 *
 * \author Juver
 * \date 2020/11/05
 *
 * 
 */

#ifndef OUTERINTERFACEGUID_H_INCLUDED__
#define OUTERINTERFACEGUID_H_INCLUDED__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//	PAGE ID
enum ET_UIGUID_OUTER
{
	SELECT_SERVER_PAGE = NO_ID + 1,
	SELECT_CHINA_AREA_PAGE,
	COPYRIGHT,
	CHINA_TITLE,
	LOGIN_PAGE,
	PASS_KEYBOARD,
	SELECT_CHARACTER_PAGE,
	CHARACTER_CREATE_PAGE,
	CHARACTER_CREATE_INFO,
	CHARACTER_CREATE_ROTATE,
	MODAL_WINDOW_OUTER,
	OUTER_UP_IMAGE,
	OUTER_DN_IMAGE,
	FULLSCREEN_OUTER,
	FULLSCREEN_OUTER_DUMMY,
	WAIT_DISPLAY,
	SECPASS_SETPAGE,
	SECPASS_CHECKPAGE,
	MESSAGE_WINDOW,
	MESSAGE_WINDOW_DUMMY,
	LOGIN_MARK,
	LOBBY_TITLE,
	REGISTER_PAGE,				/*register page, Juver, 2017/11/17 */
	USER_ACCOUNT_PAGE,			/* user account page, Juver, 2020/11/05 */
	LOGIN_DEVICE_CHECK_VERIFY_PAGE,	/* login device check, Juver, 2020/11/06 */

	/*dmk14 ingame web*/
	FORGOTPASS_PAGE,
	FORGOTPASSCHANGE_PAGE,
	SELECT_CHARACTER_PAGE_CHANGEPASS,
	SELECT_CHARACTER_PAGE_CHANGEPIN,
	SELECT_CHARACTER_PAGE_CHANGEMAIL,
	SELECT_CHARACTER_PAGE_RESETPIN,
	SELECT_CHARACTER_PAGE_TOPUP,
	SELECT_CHARACTER_PAGE_GAMETIMECONVERTUI,
	/*dmk14 ingame web*/
	OUTER_MODAL_GENERAL_FORGOTPASS_FAIL,
	OUTER_MODAL_GENERAL_FORGOTPASS_PROCEED,
	OUTER_MODAL_GENERAL_CHANGEPASS_FAIL,
	OUTER_MODAL_GENERAL_CHANGEPASS_SUCCESS,
	OUTER_MODAL_GENERAL_SELCHAR_CHANGEPASS_FAIL,
	OUTER_MODAL_GENERAL_SELCHAR_CHANGEPASS_SUCCESS,
	OUTER_MODAL_GENERAL_SELCHAR_CHANGEPIN_FAIL,
	OUTER_MODAL_GENERAL_SELCHAR_CHANGEPIN_SUCCESS,
	OUTER_MODAL_GENERAL_GAMETIME_CONVERT_FAIL,
	OUTER_MODAL_GENERAL_GAMETIME_CONVERT_SUCCESS,
	OUTER_MODAL_GENERAL_SELCHAR_RESETPIN_FAIL,
	OUTER_MODAL_GENERAL_SELCHAR_RESETPIN_SUCCESS,
	OUTER_MODAL_GENERAL_SELCHAR_TOPUP_FAIL,
	OUTER_MODAL_GENERAL_SELCHAR_TOPUP_SUCCESS,
	OUTER_MODAL_GENERAL_SELCHAR_CHANGEMAIL_FAIL,
	OUTER_MODAL_GENERAL_SELCHAR_CHANGEMAIL_SUCCESS,
};


#endif // OUTERINTERFACEGUID_H_INCLUDED__
