/*!
 * \file UIInfoLoaderDefine.h
 *
 * \author Juver
 * \date 2020/04/12
 *
 * 
 */

#ifndef UIINFOLOADERDEFINE_H_INCLUDED__
#define UIINFOLOADERDEFINE_H_INCLUDED__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


namespace NS_UIINFO_BASIC
{
	struct SINFO_TEXT
	{
		CString strText;
		DWORD dwTextColor;

		SINFO_TEXT() : strText(""), dwTextColor(0) {}
		SINFO_TEXT(CString _strText, DWORD _dwTextColor) : strText(_strText), dwTextColor(_dwTextColor) {}
	};

	enum EMSKILL_BASIC_CASE_TYPE
	{
		EMSKILL_BASIC_CASE_TYPE_NONE = 0,
		EMSKILL_BASIC_CASE_TYPE_NORMAL_INCREASE_TIMER	= 1,
		EMSKILL_BASIC_CASE_TYPE_NORMAL_DECREASE_TIMER	= 2,
		EMSKILL_BASIC_CASE_TYPE_NORMAL_INCREASE_BASIC	= 3,
		EMSKILL_BASIC_CASE_TYPE_NORMAL_DECREASE_BASIC	= 4,
		EMSKILL_BASIC_CASE_TYPE_PASSIVE_INCREASE_TIMER	= 5,
		EMSKILL_BASIC_CASE_TYPE_PASSIVE_DECREASE_TIMER	= 6,
		EMSKILL_BASIC_CASE_TYPE_PASSIVE_INCREASE_BASIC	= 7,
		EMSKILL_BASIC_CASE_TYPE_PASSIVE_DECREASE_BASIC	= 8,
	};
};





#endif // UIINFOLOADERDEFINE_H_INCLUDED__
