#ifndef NSROPTIONDEF_H__INCLUDED
#define NSROPTIONDEF_H__INCLUDED

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

namespace ROPTION
{
	enum EMTEXTUREFILTER
	{
		EMTEXTUREFILTER_TRILINEAR		= 0,
		EMTEXTUREFILTER_ANISOTROPIC_2	= 1,
		EMTEXTUREFILTER_ANISOTROPIC_4	= 2,
		EMTEXTUREFILTER_ANISOTROPIC_8	= 3,
		EMTEXTUREFILTER_ANISOTROPIC_16	= 4,
		EMTEXTUREFILTER_NSIZE			= 5,

	};

	enum EMHIDE_DEAD
	{
		EMHIDE_DEAD_NONE				= 0,
		EMHIDE_DEAD_ALL					= 1,
		EMHIDE_DEAD_OTHER_TEAM			= 2,
		EMHIDE_DEAD_SIZE				= 3,
	};
};


#endif // NSROPTIONDEF_H__INCLUDED
