#ifndef NSRPROFILEDEF_H__INCLUDED
#define NSRPROFILEDEF_H__INCLUDED

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#define	QUICK_SLOT_NUM	6
#define	QUICK_SKILL_NUM	10
#define	QUICK_MENU_NUM	17
#define	QUICK_ALL_NUM	(QUICK_SLOT_NUM + QUICK_SKILL_NUM + QUICK_MENU_NUM)
#define CHAT_MACRO_NUM	10
#define BASICMENU_NUM	12



// SHORTCUT KEY
enum
{
	SHORTCUT_INVEN = 0,
	SHORTCUT_CHAR,
	SHORTCUT_SKILL,
	SHORTCUT_PARTY,
	SHORTCUT_QUEST,
	SHORTCUT_CLUB,
	SHORTCUT_FRIEND,
	SHORTCUT_MAP,
	SHORTCUT_ITEMBANK,
	SHORTCUT_RUN,
	SHORTCUT_HELP,
	SHORTCUT_PET,
	SHORTCUT_ATTACKMODE,
	SHORTCUT_PKMODE,
	SHORTCUT_ITEMSHOP,
	SHORTCUT_CHATMACRO,
	SHORTCUT_SUMMON
};

//enum ERENDER_SETTING_TYPE
//{
//	ERENDER_SETTING_TYPE_DEFAULT		= 0,
//	ERENDER_SETTING_TYPE_HIDE_DISGUISE	= 1,
//	ERENDER_SETTING_TYPE_SIMPLIFIED		= 2,
//
//	ERENDER_SETTING_TYPE_SIZE			= 3,
//};

enum EMCHARACTER_VIEW
{
	EMCHARACTER_VIEW_ALL		= 0,
	EMCHARACTER_VIEW_SIMPLIFY	= 1,
	EMCHARACTER_VIEW_SIZE		= 2,
};

#endif // NSRPROFILEDEF_H__INCLUDED
