//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldTool.rc
//
#define ID_ADDCOLOUR                    3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_WorldToolTYPE               129
#define IDD_DLG_COLOR                   129
#define IDC_DRAGITEM                    130
#define IDD_DLG_MAIN                    310
#define IDD_PAGE_MAIN_WLD               312
#define IDD_PAGE_MAIN_PIE               313
#define IDD_PAGE_WLD_MAIN               314
#define IDD_PAGE_PIE_MAIN               315
#define IDD_PAGE_WLD_FOG                316
#define IDD_PAGE_WLD_SKY                317
#define IDD_PAGE_WLD_BGM                318
#define IDD_PAGE_WLD_SOUND              319
#define IDD_PAGE_WLD_BASIC              320
#define IDD_PAGE_WLD_EFFECT             321
#define IDC_STATIC_TOOL                 1000
#define IDC_HUE                         1003
#define IDC_STATIC_TOOL_PAGE_WLD        1003
#define IDC_BTN_PIE_LOAD                1004
#define IDC_SAT                         1004
#define IDC_BTN_PIE_SAVE                1005
#define IDC_LUM                         1005
#define IDC_EDT_PIE_FILENAME            1006
#define IDC_RED                         1006
#define IDC_BUTTON3                     1007
#define IDC_GREEN                       1007
#define IDC_BTN_WLD_LOAD                1008
#define IDC_BLUE                        1008
#define IDC_BTN_WLD_SAVE                1009
#define IDC_EDT_WLD_FILENAME            1010
#define IDC_CMB_WLD_SELECT              1011
#define IDC_BTN_WLD_SELECT              1012
#define IDC_REF                         1012
#define IDC_BTN_WLD_CLOSE               1013
#define IDC_BTN_WLD_APPLY               1014
#define IDC_CHK_NEW_RANGE               1015
#define IDC_CHK_SKY_FOG                 1016
#define IDC_LIST_SOUND                  1016
#define IDC_CHK_STATIC_RANGE            1017
#define IDC_BTN_FOG_COLOR               1018
#define IDC_EDT_FOG_COLOR_A             1019
#define IDC_EDT_FOG_COLOR_R             1020
#define IDC_CHK_SKY_ENABLE              1020
#define IDC_EDT_FOG_COLOR_G             1021
#define IDC_CHK_CLOUD_ENABLE            1021
#define IDC_EDT_FOG_COLOR_B             1022
#define IDC_EDT_AXIS_VALUE              1022
#define IDC_BTN_FOG_COLOR_DAY           1023
#define IDC_EDT_RADIO_AXIS              1023
#define IDC_EDT_FOG_COLOR_DAY_A         1024
#define IDC_BTN_BGM                     1024
#define IDC_CHK_UNKNOWN_DATA1           1024
#define IDC_EDT_FOG_COLOR_DAY_R         1025
#define IDC_EDT_BGM                     1025
#define IDC_CHK_UNKNOWN_DATA2           1025
#define IDC_EDT_FOG_COLOR_DAY_G         1026
#define IDC_STATIC_TOOL_PAGE_PIE        1026
#define IDC_EDT_FOG_COLOR_DAY_B         1027
#define IDC_BTN_SOUND_ADD               1027
#define IDC_BTN_FOG_COLOR_NIGHT         1028
#define IDC_BTN_SOUND_DEL               1028
#define IDC_EDT_FOG_COLOR_NIGHT_A       1029
#define IDC_BTN_SOUND_FILE              1029
#define IDC_EDT_FOG_COLOR_NIGHT_R       1030
#define IDC_EDT_EDIT_SOUND_NAME         1030
#define IDC_EDT_FOG_COLOR_NIGHT_G       1031
#define IDC_EDT_SOUND_FILE              1031
#define IDC_EDT_FOG_COLOR_NIGHT_B       1032
#define IDC_EDT_SOUND_RANGE_MIN         1032
#define IDC_EDT_FOG_START               1033
#define IDC_EDT_SOUND_RANGE_MAX         1033
#define IDC_EDT_FOG_END                 1034
#define IDC_EDT_SOUND_LOOP_TIME         1034
#define IDC_EDIT_CHK_LOOP               1035
#define IDC_BTN_EDIT_SAVE               1036
#define IDC_BTN_EDIT_CANCEL             1037
#define IDC_BTN_MAKE_SHADOW_MESH        1037
#define IDC_CHK_BASIC_LEGACY_SHADOW     1038
#define IDC_BTN_MAKE_SHADOW_NAVI        1038
#define IDC_EDT_BASIC_VERTEX_MULTI      1039
#define IDC_BTN_MAKE_SHADOW_NAVI2       1039
#define IDC_EDIT_EFFECT_FILE            1039
#define IDC_BTN_NAVIGATION_MESH_REPLACE 1040
#define IDC_LIST_EFFECT                 1040
#define IDC_BTN_EFFECT_ADD              1041
#define IDC_BTN_EFFECT_DEL              1042
#define IDC_BTN_EFFECT_EDIT_MATRIX      1043
#define IDC_BUTTON_EFFECT_FILE          1044
#define IDC_EDIT_EFFECT_NAME            1045
#define IDC_STATIC_EFFECT_NAME          1046
#define IDC_BUTTON_EFFECT_CANCEL        1047
#define IDC_BUTTON_EFFECT_SAVE          1048
#define IDC_BTN_EFFECT_EDIT_MATRIX2     1049
#define IDC_BTN_EFFECT_EDIT_MATRIX_CANCEL 1049
#define ID_VIEW_EDITORTOOLBAR           32771
#define ID_RENDER_DEBUGINFO             32772
#define ID_CAMERA_SPEED500              32773
#define ID_CAMERA_SPEED1000             32774
#define ID_CAMERA_SPEED1500             32775
#define ID_CAMERA_SPEEDDEFAULT          32776
#define ID_CAMERA_RESETPOSITION         32777
#define ID_FOGRANGE_RANGE5K             32778
#define ID_FOGRANGE_RANGE10K            32779
#define ID_FOGRANGE_RANGE20K            32780
#define ID_FOGRANGE_RANGE50K            32781
#define ID_FOGRANGE_RANGEDEFAULT        32782
#define ID_SKY_BLUETIME                 32783
#define ID_SKY_REDTIME                  32784
#define ID_SKY_NOONTIME                 32785
#define ID_SKY_NIGHTTIME                32786
#define ID_SKY_FADEOUT                  32787
#define ID_SKY_FADEIN                   32788
#define ID_WEATHER_WEATHERRAIN          32789
#define ID_WEATHER_WEATHERSNOW          32790
#define ID_WEATHER_WEATHERLEAVES        32791
#define ID_WEATHER_WEATHERSPORE         32792
#define ID_LIGHTMAN_POINTLIGHTRENDER    32793
#define ID_LIGHTMAN_LIGHTNAMERENDER     32794
#define ID_FOGRANGE_RANGE               32795
#define ID_FOGRANGE_RANGEDEFAULTMID     32796
#define ID_RENDER_SOUNDMANRANGERENDER   32797
#define ID_RENDER_SOUNDMANNAMERENDER    32798
#define ID_RENDER_SHOWPOSITIONSPHERE    32799
#define ID_RENDER_RENDERSHADOWWIREFRAME 32800
#define ID_RENDER_PIECEUSECOLLISION     32802
#define ID_RENDER_PIECEUSEDISTANCE      32803
#define ID_RENDER_RENDEREFFECTAABB      32804
#define ID_RENDER_RENDEREFFECTNAME      32805
#define ID_EDIT_EDITMATRIXMOVE          32806
#define ID_EDIT_EDITMATRIXROTATE        32808
#define ID_EDIT_EDITMATRIXSCALE         32811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
