#pragma once


enum EMWLD_PAGE
{
	EMWLD_PAGE_MAIN			= 0,
	EMWLD_PAGE_BASIC		= 1,
	EMWLD_PAGE_FOG			= 2,
	EMWLD_PAGE_SKY			= 3,
	EMWLD_PAGE_BGM			= 4,
	EMWLD_PAGE_SOUND		= 5,
	EMWLD_PAGE_EFFECT		= 6,
	EMWLD_PAGE_SIZE			= 7,
};


enum EMPIECE_PAGE
{
	EMPIECE_PAGE_MAIN		= 0,
	EMPIECE_PAGE_SIZE		= 1,
};