/*!
 * \file SearchDefine.h
 *
 * \author Juver
 * \date 2021/07/14
 *
 * 
 */

#ifndef SEARCHDEFINE_H_INCLUDED__
#define SEARCHDEFINE_H_INCLUDED__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


enum EMSEARCH
{
	EMSEARCH_NAME	= 0,
	EMSEARCH_MID	= 1,
	EMSEARCH_SID	= 2,
	EMSEARCH_EFFECT	= 3,
	EMSEARCH_DDS	= 4,
	EMSEARCH_DDSXY	= 5,
	EMSEARCH_SKILL_ANIMAIN	= 6,
	EMSEARCH_SKILL_ANISUB	= 7,
	EMSEARCH_SKILL_APPLYTYPE	= 8,
	EMSEARCH_SKILL_STATETROUBLE	= 9,
	EMSEARCH_SKILL_IMPACTADDON	= 10,
	EMSEARCH_SKILL_SPECADDON	= 11,
	EMSEARCH_SKILL_SPECIALTYPE	= 12,
	EMSEARCH_SKILL_ACTIONTYPE	= 13,
	EMSEARCH_SKILL_IMPACT_SIDE	= 14,
	EMSEARCH_SKILL_IMPACT_TAR	= 15,
	EMSEARCH_SKILL_IMPACT_REALM	= 16,

	EMSEARCH_TOTAL	= 17,
};


struct SSEARCH
{
	SNATIVEID	sID;
	std::string strNAME;
	std::string strFIND;

	SSEARCH () 
	{
		sID = NATIVEID_NULL();
		strNAME = "";
		strFIND = "";
	};
};

#endif // SEARCHDEFINE_H_INCLUDED__

