#ifndef GLBATTLEPASS_DEFINE_H_
#define GLBATTLEPASS_DEFINE_H_

/*12-9-14, Battle Pass - CNDev*/

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define BATTLEPASS_TITLE_MSG_SIZE		250
#define BATTLEPASS_DAILY_MISSION_MAX	8

enum EMBATTLEPASS_TYPE
{
	EMBATTLEPASS_TYPE_KILL_MOB			= 0,
	EMBATTLEPASS_TYPE_KILL_PLAYER		= 1,
	EMBATTLEPASS_TYPE_REACH_MAP			= 2,
	EMBATTLEPASS_TYPE_TAKE_ITEM			= 3,
	EMBATTLEPASS_TYPE_USE_ITEM			= 4,
	EMBATTLEPASS_TYPE_TRADE_PLAYER		= 5,
	EMBATTLEPASS_TYPE_WHISPER_PLAYER	= 6,
	EMBATTLEPASS_TYPE_PRIVATE_MARKET	= 7,
	EMBATTLEPASS_TYPE_GAIN_PLAYTIME		= 8,
	EMBATTLEPASS_TYPE_GAIN_GOLD			= 9,
	EMBATTLEPASS_TYPE_GAIN_CONTRIPOINT	= 10,
	EMBATTLEPASS_TYPE_SIZE				= 11,
};

namespace COMMENT
{
	extern std::string BATTLEPASS_MID[EMBATTLEPASS_TYPE_SIZE];
};

#endif // GLBATTLEPASS_DEFINE_H_
