#pragma once


/*event map move, Juver, 2017/08/25 */
enum EMEVENT_MOVEMAP_FB
{
	EMEVENT_MOVEMAP_FB_FAIL			= 0,
	EMEVENT_MOVEMAP_FB_CONDITION	= 1,
	EMEVENT_MOVEMAP_FB_OK			= 2,
};

/*charinfoview , Juver, 2017/11/11 */
enum EMREQ_CHARINFO_FB
{
	EMREQ_CHARINFO_FB_FAIL				= 0,
	EMREQ_CHARINFO_FB_INVALID_TARGET	= 1,
	EMREQ_CHARINFO_FB_TIMEDELAY			= 2,
	EMREQ_CHARINFO_FB_WEARINFO			= 3,
};

/* charinfoview, Juver, 2020/03/03 */
enum EMREQ_CHARINFO_AGT_FB
{
	EMREQ_CHARINFO_AGT_FB_FAIL			= 0,
	EMREQ_CHARINFO_AGT_FB_WEAR_INFO		= 1,
};


/*bike color , Juver, 2017/11/13 */
enum EMREQ_CHANGE_BIKE_COLOR_FB
{
	EMREQ_CHANGE_BIKE_COLOR_FB_CHANGE_FAIL			= 0,
	EMREQ_CHANGE_BIKE_COLOR_FB_INVALID_CARD			= 1,
	EMREQ_CHANGE_BIKE_COLOR_FB_VEHICLE_INACTIVE		= 2,
	EMREQ_CHANGE_BIKE_COLOR_FB_VEHICLE_NOT_BIKE		= 3,
	EMREQ_CHANGE_BIKE_COLOR_FB_VEHICLE_NOT_COLOR	= 4,
	EMREQ_CHANGE_BIKE_COLOR_FB_CHANGE_DONE			= 5,
};

/*change scale card, Juver, 2018/01/04 */
enum EMFB_CHANGE_SCALE
{
	EMFB_CHANGE_SCALE_FAIL		= 0,
	EMFB_CHANGE_SCALE_OK		= 1,
	EMFB_CHANGE_SCALE_NOT_CARD	= 2,
};

/*item color, Juver, 2018/01/10 */
enum EMFB_ITEM_COLOR_CHANGE
{
	EMFB_ITEM_COLOR_CHANGE_FAILED		= 0,
	EMFB_ITEM_COLOR_CHANGE_NOT_CARD		= 1,
	EMFB_ITEM_COLOR_CHANGE_SLOT_ERROR	= 2,
	EMFB_ITEM_COLOR_CHANGE_DONE			= 3,
};

/*item wrapper, Juver, 2018/01/11 */
enum EMFB_ITEM_WRAP
{
	EMFB_ITEM_WRAP_FAILED				= 0,
	EMFB_ITEM_WRAP_TARGET_NOT_VALID		= 1,
	EMFB_ITEM_WRAP_TARGET_HAVE_DISGUISE	= 2,
	EMFB_ITEM_WRAP_HOLD_INVALID			= 3,
	EMFB_ITEM_WRAP_HOLD_NOT_WRAPPER		= 4,
	EMFB_ITEM_WRAP_HOLD_NOT_BOX			= 5,
	EMFB_ITEM_WRAP_TARGET_NO_NEED		= 6,
	EMFB_ITEM_WRAP_DONE					= 7,
};

/*item wrapper, Juver, 2018/01/12 */
enum EMFB_ITEM_UNWRAP
{
	EMFB_ITEM_UNWRAP_FAILED				= 0,
	EMFB_ITEM_UNWRAP_TARGET_NOT_VALID	= 1,
	EMFB_ITEM_UNWRAP_DONE				= 2,
};

/*change school card, Juver, 2018/01/12 */
enum EMFB_CHANGE_SCHOOL
{
	EMFB_CHANGE_SCHOOL_FAILED			= 0,
	EMFB_CHANGE_SCHOOL_NOT_CARD			= 1,
	EMFB_CHANGE_SCHOOL_NOT_SELECTED		= 2,
	EMFB_CHANGE_SCHOOL_REQ_CLEAN_QUEST	= 3,
	EMFB_CHANGE_SCHOOL_REQ_CLEAN_GUILD	= 4,
	EMFB_CHANGE_SCHOOL_REQ_MAX_LEVEL	= 5,
	EMFB_CHANGE_SCHOOL_SAME_SCHOOL		= 6,
	EMFB_CHANGE_SCHOOL_DONE				= 7,
};

/*item transfer card, Juver, 2018/01/18 */
enum EMFB_ITEM_TRANSFER
{
	EMFB_ITEM_TRANSFER_FAILED				= 0,
	EMFB_ITEM_TRANSFER_NOT_CARD				= 1,
	EMFB_ITEM_TRANSFER_INVALID_ITEM			= 2,
	EMFB_ITEM_TRANSFER_INVALID_ITEM_TYPE	= 3,
	EMFB_ITEM_TRANSFER_TIME_LIMIT			= 4,
	EMFB_ITEM_TRANSFER_DISGUISE				= 5,
	EMFB_ITEM_TRANSFER_SUIT_MISMATCH		= 6,
	EMFB_ITEM_TRANSFER_ATTACK_MISMATCH		= 7,
	EMFB_ITEM_TRANSFER_COST					= 8,
	EMFB_ITEM_TRANSFER_HAVE_DISGUISE		= 9,
	EMFB_ITEM_TRANSFER_NOT_TRANSFER_ITEM	= 10,
	EMFB_ITEM_TRANSFER_DONE					= 11,
};

/* car, cart color, Juver, 2018/02/14 */
enum EMREQ_CHANGE_CAR_COLOR_FB
{
	EMREQ_CHANGE_CAR_COLOR_FB_CHANGE_FAIL		= 0,
	EMREQ_CHANGE_CAR_COLOR_FB_INVALID_CARD		= 1,
	EMREQ_CHANGE_CAR_COLOR_FB_VEHICLE_INACTIVE	= 2,
	EMREQ_CHANGE_CAR_COLOR_FB_VEHICLE_NOT_CAR	= 3,
	EMREQ_CHANGE_CAR_COLOR_FB_VEHICLE_NOT_COLOR	= 4,
	EMREQ_CHANGE_CAR_COLOR_FB_CHANGE_DONE		= 5,
};

/* booster all vehicle, Juver, 2018/02/14 */
enum EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB
{
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_OK				= 0,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_FAIL				= 1,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_INVALID_CARD		= 2,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_INVALID_ITEM		= 3,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_INVALID_TYPE		= 4,
	EMALLVEHICLE_REQ_ENABLE_BOOSTER_FB_ALREADY_ENABLED	= 5,
};

/* additional gm commands, Juver, 2018/03/01 */
enum EMREQ_GM_ITEM_FB
{
	EMREQ_GM_ITEM_FB_OK					= 0,
	EMREQ_GM_ITEM_FB_FAIL				= 1,
	EMREQ_GM_ITEM_FB_INVALID_PASS		= 2,
	EMREQ_GM_ITEM_FB_INVALID_ITEM		= 3,
	EMREQ_GM_ITEM_FB_INVEN_SPACE		= 4,
};

/* additional gm commands, Juver, 2018/03/01 */
enum EMREQ_GM_INVEN_OPEN_FB
{
	EMREQ_GM_INVEN_OPEN_FB_OK				= 0,
	EMREQ_GM_INVEN_OPEN_FB_FAIL				= 1,
	EMREQ_GM_INVEN_OPEN_FB_INVALID_PASS		= 2,
};

/* additional gm commands, Juver, 2018/03/01 */
enum EMREQ_GM_SKILL_FB
{
	EMREQ_GM_SKILL_FB_OK				= 0,
	EMREQ_GM_SKILL_FB_FAIL				= 1,
	EMREQ_GM_SKILL_FB_INVALID_PASS		= 2,
	EMREQ_GM_SKILL_FB_INVALID_SKILL		= 3,
	EMREQ_GM_SKILL_FB_CANNOT_LEARN		= 4,
};

/* additional gm commands, Juver, 2018/03/02 */
enum EMREQ_GM_LEVEL_FB
{
	EMREQ_GM_LEVEL_FB_OK				= 0,
	EMREQ_GM_LEVEL_FB_FAIL				= 1,
	EMREQ_GM_LEVEL_FB_INVALID_PASS		= 2,
	EMREQ_GM_LEVEL_FB_MAX_LEVEL			= 3,
};

/* additional gm commands, Juver, 2018/03/02 */
enum EMREQ_GM_STATS_FB
{
	EMREQ_GM_STATS_FB_OK				= 0,
	EMREQ_GM_STATS_FB_FAIL				= 1,
	EMREQ_GM_STATS_FB_INVALID_PASS		= 2,
};

/* additional gm commands, Juver, 2018/03/02 */
enum EMREQ_GM_STATSP_FB
{
	EMREQ_GM_STATSP_FB_OK				= 0,
	EMREQ_GM_STATSP_FB_FAIL				= 1,
	EMREQ_GM_STATSP_FB_INVALID_PASS		= 2,
};

/* additional gm commands, Juver, 2018/03/02 */
enum EMREQ_GM_SKILLP_FB
{
	EMREQ_GM_SKILLP_FB_OK				= 0,
	EMREQ_GM_SKILLP_FB_FAIL				= 1,
	EMREQ_GM_SKILLP_FB_INVALID_PASS		= 2,
};

/*item random option rebuild, Juver, 2018/07/04 */
enum EMFB_ITEM_RANDOM_OPTION_REBUILD
{
	EMFB_ITEM_RANDOM_OPTION_REBUILD_FAILED				= 0,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_NOT_CARD			= 1,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_NOT_TARGET			= 2,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_TARGET_NOT_SUIT		= 3,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_TARGET_NOT_RANDOM	= 4,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_TARGET_DESTROYED	= 5,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_SUCCESS				= 6,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_SELECT_ERROR		= 7,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_DELAY_TIME			= 8,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_TASK_ACTIVE			= 9,
	EMFB_ITEM_RANDOM_OPTION_REBUILD_TARGET_MAXED		= 10,		/* Item Reform use limit, Juver, 2021/07/23 */
};

/*inventory sort, Juver, 2018/07/07 */
enum EMFB_ITEM_INVEN_SORT
{
	EMFB_ITEM_INVEN_SORT_FAILED		= 0,
	EMFB_ITEM_INVEN_SORT_DELAY		= 1,
	EMFB_ITEM_INVEN_SORT_DONE		= 2,
	EMFB_ITEM_INVEN_SORT_DISABLED	= 3,
};

///*hide costume, EJCode, 2018/11/18 */
//enum EMFB_HIDE_COSTUME
//{
//	EMFB_HIDE_COSTUME_DELAY_TIME	= 0,
//	EMFB_HIDE_COSTUME_OK			= 1,
//};

/*gm command send item, Juver, 2019/03/23 */
enum EMREQ_GM_SEND_ITEM_FB
{
	EMREQ_GM_SEND_ITEM_FB_OK				= 0,
	EMREQ_GM_SEND_ITEM_FB_FAIL				= 1,
	EMREQ_GM_SEND_ITEM_FB_INVALID_PASS		= 2,
	EMREQ_GM_SEND_ITEM_FB_INVALID_ITEM		= 3,
	EMREQ_GM_SEND_ITEM_FB_NO_INVEN_SPACE	= 4,
	EMREQ_GM_SEND_ITEM_FB_INVALID_CHARACTER	= 5,
};

enum EMREQ_GM_GET_CROW_TIME_FB
{
	EMREQ_GM_GET_CROW_TIME_FB_OK				= 0,
	EMREQ_GM_GET_CROW_TIME_FB_FAIL				= 1,
	EMREQ_GM_GET_CROW_TIME_FB_INVALID_PASS		= 2,
	EMREQ_GM_GET_CROW_TIME_FB_INVALID_CROW		= 3,
	EMREQ_GM_GET_CROW_TIME_FB_INVALID_MAP		= 4,
	EMREQ_GM_GET_CROW_TIME_FB_CROW_FIND			= 5,
};

enum EMREQ_GM_EVENT_CONTRI_TYRANNY_FB
{
	EMREQ_GM_EVENT_CONTRI_TYRANNY_FB_OK				= 0,
	EMREQ_GM_EVENT_CONTRI_TYRANNY_FB_FAIL			= 1,
	EMREQ_GM_EVENT_CONTRI_TYRANNY_FB_INVALID_PASS	= 2,
	EMREQ_GM_EVENT_CONTRI_TYRANNY_FB_INVALID_RATE	= 3,
};

enum EMREQ_GM_EVENT_CONTRI_SCHOOL_WAR_FB
{
	EMREQ_GM_EVENT_CONTRI_SCHOOL_WAR_FB_OK				= 0,
	EMREQ_GM_EVENT_CONTRI_SCHOOL_WAR_FB_FAIL			= 1,
	EMREQ_GM_EVENT_CONTRI_SCHOOL_WAR_FB_INVALID_PASS	= 2,
	EMREQ_GM_EVENT_CONTRI_SCHOOL_WAR_FB_INVALID_RATE	= 3,
};

enum EMREQ_GM_EVENT_CONTRI_CAPTURE_THE_FLAG_FB
{
	EMREQ_GM_EVENT_CONTRI_CAPTURE_THE_FLAG_FB_OK			= 0,
	EMREQ_GM_EVENT_CONTRI_CAPTURE_THE_FLAG_FB_FAIL			= 1,
	EMREQ_GM_EVENT_CONTRI_CAPTURE_THE_FLAG_FB_INVALID_PASS	= 2,
	EMREQ_GM_EVENT_CONTRI_CAPTURE_THE_FLAG_FB_INVALID_RATE	= 3,
};

enum EMREQ_CURRENCY_SHOP_PURCHASE_FB
{
	EMREQ_CURRENCY_SHOP_PURCHASE_ERROR						= 0,
	EMREQ_CURRENCY_SHOP_PURCHASE_INVALID_CROW				= 1,
	EMREQ_CURRENCY_SHOP_PURCHASE_INVALID_SHOP				= 2,
	EMREQ_CURRENCY_SHOP_PURCHASE_INVALID_SHOP_ITEM			= 3,
	EMREQ_CURRENCY_SHOP_PURCHASE_INVALID_ITEM_DATA			= 4,
	EMREQ_CURRENCY_SHOP_PURCHASE_NOT_ENOUGH_MONEY			= 5,
	EMREQ_CURRENCY_SHOP_PURCHASE_NOT_ENOUGH_GAME_POINTS		= 6,
	EMREQ_CURRENCY_SHOP_PURCHASE_NOT_ENOUGH_WAR_CHIPS		= 7,
	EMREQ_CURRENCY_SHOP_PURCHASE_NOT_ENOUGH_INVEN_SPACE		= 8,
	EMREQ_CURRENCY_SHOP_PURCHASE_ERROR_COST					= 9,
	EMREQ_CURRENCY_SHOP_PURCHASE_ERROR_INSERT				= 10,
	EMREQ_CURRENCY_SHOP_PURCHASE_DELAY						= 11,

	EMREQ_CURRENCY_SHOP_PURCHASE_DONE						= 12,
};

enum EMREQ_GM_KICKOUT_FB
{
	EMREQ_GM_KICKOUT_FB_FAIL		= 0,
	EMREQ_GM_KICKOUT_FB_NOT_GM		= 1,
	EMREQ_GM_KICKOUT_FB_WRONG_PASS	= 2,
	EMREQ_GM_KICKOUT_FB_TIME_LOW	= 3,
	EMREQ_GM_KICKOUT_FB_TIME_HIGH	= 4,
	EMREQ_GM_KICKOUT_FB_DELETE_DONE = 5,
	EMREQ_GM_KICKOUT_FB_DELETE_FAIL = 6,
	EMREQ_GM_KICKOUT_FB_UPDATE_DONE = 7,
	EMREQ_GM_KICKOUT_FB_ADDED_DONE	= 8,
};


/* personal lock system, Juver, 2019/12/12 */
enum EMREQ_PERSONAL_LOCK_REQUEST
{
	EMREQ_PERSONAL_LOCK_REQUEST_FAIL				= 0,
	EMREQ_PERSONAL_LOCK_REQUEST_FUNCTION_DISABLED	= 1,
	EMREQ_PERSONAL_LOCK_REQUEST_INVALID_LOCK_TYPE	= 2,
	EMREQ_PERSONAL_LOCK_REQUEST_REQUIRE_TIME		= 3,
	EMREQ_PERSONAL_LOCK_REQUEST_PIN_TO_CREATE		= 4,
	EMREQ_PERSONAL_LOCK_REQUEST_PIN_TO_INPUT		= 5,
};

/* personal lock system, Juver, 2019/12/13 */
enum EMFB_PERSONAL_LOCK_CREATE_PIN
{
	EMFB_PERSONAL_LOCK_CREATE_PIN_FAILED				= 0,
	EMFB_PERSONAL_LOCK_CREATE_PIN_FUNCTION_DISABLED		= 1,
	EMFB_PERSONAL_LOCK_CREATE_PIN_INVALID_LOCK_TYPE		= 2,
	EMFB_PERSONAL_LOCK_CREATE_PIN_ALREADY_ENABLED		= 3,
	EMFB_PERSONAL_LOCK_CREATE_PIN_KEY_EMPTY				= 4,
	EMFB_PERSONAL_LOCK_CREATE_PIN_KEY_SIZE				= 5,
	EMFB_PERSONAL_LOCK_CREATE_PIN_KEY_MISMATCH			= 6,
	EMFB_PERSONAL_LOCK_CREATE_PIN_KEY_NUMBER_ONLY		= 7,
	EMFB_PERSONAL_LOCK_CREATE_PIN_TIME_OUT				= 8,
	EMFB_PERSONAL_LOCK_CREATE_PIN_PUTON_DONE			= 9,
};

/* personal lock system, Juver, 2019/12/13 */
enum EMFB_PERSONAL_LOCK_INPUT_PIN
{
	EMFB_PERSONAL_LOCK_INPUT_PIN_FAILED					= 0,
	EMFB_PERSONAL_LOCK_INPUT_PIN_FUNCTION_DISABLED		= 1,
	EMFB_PERSONAL_LOCK_INPUT_PIN_INVALID_LOCK_TYPE		= 2,
	EMFB_PERSONAL_LOCK_INPUT_PIN_KEY_EMPTY				= 3,
	EMFB_PERSONAL_LOCK_INPUT_PIN_KEY_SIZE				= 4,
	EMFB_PERSONAL_LOCK_INPUT_PIN_KEY_NUMBER_ONLY		= 5,
	EMFB_PERSONAL_LOCK_INPUT_PIN_TIME_OUT				= 6,
	EMFB_PERSONAL_LOCK_INPUT_PIN_KEY_WRONG				= 7,
	EMFB_PERSONAL_LOCK_INPUT_PIN_KEY_WRONG_MAXED		= 8,
	EMFB_PERSONAL_LOCK_INPUT_PIN_DONE					= 9,
};

/* personal lock system, Juver, 2019/12/11 */
enum EMFB_PERSONAL_LOCK_PIN_RESET
{
	EMFB_PERSONAL_LOCK_PIN_RESET_FAILED					= 0,
	EMFB_PERSONAL_LOCK_PIN_RESET_FUNCTION_DISABLED		= 1,
	EMFB_PERSONAL_LOCK_PIN_RESET_INVALID_LOCK_TYPE		= 2,
	EMFB_PERSONAL_LOCK_PIN_RESET_TIME_OUT				= 3,
	EMFB_PERSONAL_LOCK_PIN_RESET_NOT_CARD				= 4,
	EMFB_PERSONAL_LOCK_PIN_RESET_DONE					= 5,
};

/* personal lock system, Juver, 2020/01/29 */
enum EMFB_PERSONAL_LOCK_PIN_CHANGE
{
	EMFB_PERSONAL_LOCK_PIN_CHANGE_FAILED				= 0,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_FUNCTION_DISABLED		= 1,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_INVALID_LOCK_TYPE		= 2,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_NOT_CARD				= 3,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_PIN_EMPTY				= 4,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_PIN_SIZE				= 5,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_PIN_NUMBER_ONLY		= 6,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_PIN_MISMATCH			= 7,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_PIN_INCORRECT			= 8,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_PIN_DONE				= 9,
	EMFB_PERSONAL_LOCK_PIN_CHANGE_TIME_OUT				= 10,

};

/* personal lock system, Juver, 2020/01/31 */
enum EMFB_PERSONAL_LOCK_PIN_RECOVER
{
	EMFB_PERSONAL_LOCK_PIN_RECOVER_FAILED					= 0,
	EMFB_PERSONAL_LOCK_PIN_RECOVER_FUNCTION_DISABLED		= 1,
	EMFB_PERSONAL_LOCK_PIN_RECOVER_INVALID_LOCK_TYPE		= 2,
	EMFB_PERSONAL_LOCK_PIN_RECOVER_TIME_OUT					= 3,
	EMFB_PERSONAL_LOCK_PIN_RECOVER_NOT_CARD					= 4,
	EMFB_PERSONAL_LOCK_PIN_RECOVER_DONE						= 5,
};

/* party finder, Juver, 2020/01/03 */
enum EMPARTY_FINDER_SEARCH_FB
{
	EMPARTY_FINDER_SEARCH_FB_FAIL					= 0,
	EMPARTY_FINDER_SEARCH_FB_FUNCTION_DISABLED		= 1,
	EMPARTY_FINDER_SEARCH_FB_INVALID_TYPE			= 2,
	EMPARTY_FINDER_SEARCH_FB_REQUIRE_TIME			= 3,
	EMPARTY_FINDER_SEARCH_FB_START_SEARCH			= 4,
};

/* party finder, Juver, 2020/01/16 */
enum EMPARTY_FINDER_JOIN_FB
{
	EMPARTY_FINDER_JOIN_FB_FAIL						= 0,
	EMPARTY_FINDER_JOIN_FB_FUNCTION_DISABLED		= 1,
	EMPARTY_FINDER_JOIN_FB_INVALID_PARTY			= 2,
	EMPARTY_FINDER_JOIN_FB_REQUIRE_TIME				= 3,
	EMPARTY_FINDER_JOIN_FB_PARTY_PRIVATE			= 4,
	EMPARTY_FINDER_JOIN_FB_REQUEST_SENT				= 5,
	EMPARTY_FINDER_JOIN_FB_PARTY_FULL				= 6,
	EMPARTY_FINDER_JOIN_FB_IN_PARTY					= 7,
	EMPARTY_FINDER_JOIN_FB_DECLINE					= 8,

	EMPARTY_FINDER_JOIN_FB_CLUB_BATTLE				= 9,
	EMPARTY_FINDER_JOIN_FB_MAP_PARTY_BLOCK_LEADER	= 10,
	EMPARTY_FINDER_JOIN_FB_MAP_PARTY_BLOCK_MEMBER	= 11,
};

enum EMREQ_GM_PCID_FB
{
	EMREQ_GM_PCID_FB_FAIL			= 0,
	EMREQ_GM_PCID_FB_NOT_GM			= 1,
	EMREQ_GM_PCID_FB_WRONG_PASS		= 2,
	EMREQ_GM_PCID_FB_INVALID_TARGET	= 3,
	EMREQ_GM_PCID_FB_REPLY			= 4,
};

/* user flag restricted, Juver, 2020/04/21 */
enum EMREQ_GM_USER_RESTRICT_FB
{
	EMREQ_GM_USER_RESTRICT_FB_FAIL				= 0,
	EMREQ_GM_USER_RESTRICT_FB_NOT_GM			= 1,
	EMREQ_GM_USER_RESTRICT_FB_WRONG_PASS		= 2,
	EMREQ_GM_USER_RESTRICT_FB_INVALID_TARGET	= 3,
	EMREQ_GM_USER_RESTRICT_FB_DONE				= 4,
};

/* gm command inven clear, Juver, 2020/05/09 */
enum EMREQ_GM_INVEN_CLEAR_FB
{
	EMREQ_GM_INVEN_CLEAR_FB_FAILED				= 0,
	EMREQ_GM_INVEN_CLEAR_FB_NOT_GM				= 1,
	EMREQ_GM_INVEN_CLEAR_FB_INVALID_PASS		= 2,
	EMREQ_GM_INVEN_CLEAR_FB_SUCCESS				= 3,
};

/* award title, Juver, 2021/02/13 */
enum EMREQ_AWARD_TITLE_SELECT_FB
{
	EMREQ_AWARD_TITLE_SELECT_FB_FAILED			= 0,
	EMREQ_AWARD_TITLE_SELECT_FB_DELAY			= 1,
	EMREQ_AWARD_TITLE_SELECT_FB_INVALID_TYPE	= 2,
	EMREQ_AWARD_TITLE_SELECT_FB_DONE			= 3,
};


/* game notice, Juver, 2021/06/12 */
enum EMREQ_GM_GAME_NOTICE_RELOAD_FB
{
	EMREQ_GM_GAME_NOTICE_RELOAD_FB_OK				= 0,
	EMREQ_GM_GAME_NOTICE_RELOAD_FB_FAIL				= 1,
	EMREQ_GM_GAME_NOTICE_RELOAD_FB_INVALID_PASS		= 2,
};

/* variable check, Juver, 2021/07/02 */
enum EMVARIABLE_CHECK
{
	EMVARIABLE_CHECK_NONE			= 0,
	EMVARIABLE_CHECK_STUN			= 1,
	EMVARIABLE_CHECK_PIERCE			= 2,
	EMVARIABLE_CHECK_TARGET_RANGE	= 3,
	EMVARIABLE_CHECK_ATTACK_RANGE	= 4,
	EMVARIABLE_CHECK_APPLY_RANGE	= 5,
};

/* chaos machine, Juver, 2021/07/10 */
enum EMFB_CHAOS_MACHINE
{
	EMFB_CHAOS_MACHINE_ERROR			= 0,
	EMFB_CHAOS_MACHINE_INVALID_ITEM		= 1,
	EMFB_CHAOS_MACHINE_INVALID_NPC		= 2,
	EMFB_CHAOS_MACHINE_NON_DROP			= 3,
	EMFB_CHAOS_MACHINE_COST				= 4,
	EMFB_CHAOS_MACHINE_NO_INVEN_SPACE	= 5,
	EMFB_CHAOS_MACHINE_NO_MATERIAL		= 6,
	EMFB_CHAOS_MACHINE_FAILED_DELETE	= 7,
	EMFB_CHAOS_MACHINE_FAILED			= 8, 
	EMFB_CHAOS_MACHINE_SUCCESS			= 9,
};

enum EMREQ_GM_GIS_RELOAD_FB
{
	EMREQ_GM_GIS_RELOAD_FB_OK				= 0,
	EMREQ_GM_GIS_RELOAD_FB_FAIL				= 1,
	EMREQ_GM_GIS_RELOAD_FB_INVALID_PASS		= 2,
	EMREQ_GM_GIS_RELOAD_FB_RELOADING		= 3,
};

enum EMREQ_PURCHASE_SKILL_FB
{
	EMREQ_PURCHASE_SKILL_FB_FAIL				= 0,
	EMREQ_PURCHASE_SKILL_FB_ALREADY_LEARNED		= 1,
	EMREQ_PURCHASE_SKILL_FB_REQ_STATS			= 2,
	EMREQ_PURCHASE_SKILL_FB_REQ_COST			= 3,
	EMREQ_PURCHASE_SKILL_FB_CANNOT_PURCHASE		= 4,
};

enum EMREQ_AUTO_POTION_FB
{
	EMREQ_AUTO_POTION_FB_FAIL				= 0,
	EMREQ_AUTO_POTION_FB_INVALID_VALUE		= 1,
	EMREQ_AUTO_POTION_FB_DONE				= 2,
	EMREQ_AUTO_POTION_FB_NOT_MAP			= 3,
};

enum EMREQ_AUTO_PILOT_FB
{
	EMREQ_AUTO_PILOT_FB_FAIL				= 0,
	EMREQ_AUTO_PILOT_FB_INVALID_VALUE		= 1,
	EMREQ_AUTO_PILOT_FB_DONE				= 2,
	EMREQ_AUTO_PILOT_FB_NOT_MAP				= 3,
};

enum EMINVEN_CARD_REBORN_FB
{
	EMINVEN_CARD_REBORN_FB_FAIL			= 0,
	EMINVEN_CARD_REBORN_FB_OK			= 1,
	EMINVEN_CARD_REBORN_FB_CLOSE		= 2,
	EMINVEN_CARD_REBORN_FB_NOITEMINVEN	= 3,
	EMINVEN_CARD_REBORN_FB_NOITEMDATA	= 4,
	EMINVEN_CARD_REBORN_FB_NOITEMTYPE	= 5,
	EMINVEN_CARD_REBORN_FB_NOMONEY		= 6,
	EMINVEN_CARD_REBORN_FB_NOLEVEL		= 7,
};

enum EMEXCHANGE_ITEM_FB
{
	EMEXCHANGE_ITEM_ERROR				= 0,
	EMEXCHANGE_ITEM_CARD_ERROR			= 1,
	EMEXCHANGE_ITEM_ITEM_ERROR			= 2,
	EMEXCHANGE_ITEM_ITEMTYPE_ERROR		= 3,
	EMEXCHANGE_ITEM_INVALID_ITEM		= 4,
	EMEXCHANGE_ITEM_ERROR_NOCIP			= 5,
	EMEXCHANGE_ITEM_DONE				= 6
};

enum EMEXCHANGE_ITEM_POINT
{
	EMEXCHANGE_ITEM_POINT_ERROR			= 0,
	EMEXCHANGE_ITEM_POINT_CARD_ERROR	= 1,
	EMEXCHANGE_ITEM_POINT_CARD_DONE		= 2,
};

enum EMCAPTCHA_CA
{
	EMCAPTCHA_CA_ERROR		= 0,
	EMCAPTCHA_CA_INCORRECT	= 1,
	EMCAPTCHA_CA_SUCCESS	= 2,
};