/*!
 * \file GLCodexDefine.h
 *
 * \author Juver
 * \date October 2017
 *
 * 
 */

#ifndef GLCODEX_DEFINE_H_
#define GLCODEX_DEFINE_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define CODEX_TITLE_MSG_SIZE 250
#define CHARACTER_BADGE_TIME 2.0f


enum EMCODEX_NOTIFY
{
	EMCODEX_NOTIFY_NONE			= 0,
	EMCODEX_NOTIFY_AROUND		= 1,
	EMCODEX_NOTIFY_ALLSERVER		= 2,
	EMCODEX_NOTIFY_SIZE			= 3,
};

enum EMCODEX_TYPE
{
	EMCODEX_TYPE_REACH_LEVEL		= 0,
	EMCODEX_TYPE_KILL_MOB		= 1,
	EMCODEX_TYPE_KILL_PLAYER		= 2,
	EMCODEX_TYPE_REACH_MAP		= 3,
	EMCODEX_TYPE_TAKE_ITEM		= 4,
	EMCODEX_TYPE_USE_ITEM		= 5,
	EMCODEX_TYPE_REACH_CODEX	= 6,
	EMCODEX_TYPE_COMPLETE_QUEST	= 7,
	EMCODEX_TYPE_CODEX_POINT	= 8,
	EMCODEX_TYPE_QUESTION_BOX	= 9,
	EMCODEX_TYPE_ETC			= 10,
	EMCODEX_TYPE_SIZE			= 11,
};

namespace COMMENT
{
	extern std::string CODEX_NOTIFY[EMCODEX_NOTIFY_SIZE];
	extern std::string CODEX_MID[EMCODEX_TYPE_SIZE];
};

#endif // GLCODEX_DEFINE_H_
