#pragma once

enum WOE_REGISTER_FB
{
	WOE_REGISTER_FB_FAILED			= 0,
	WOE_REGISTER_FB_NOTPOSSIBLE		= 1,
	WOE_REGISTER_FB_INVALID_CHANNEL	= 2,
	WOE_REGISTER_FB_INVALID_CHARID	= 3,
	WOE_REGISTER_FB_INVALID_SCHOOL	= 4,
	WOE_REGISTER_FB_LEVEL_LOW		= 5,

	WOE_REGISTER_FB_ALREADY_REG		= 6,
	WOE_REGISTER_FB_ALREADY_QUEUE	= 7,
	WOE_REGISTER_FB_QUEUED			= 8,
	WOE_REGISTER_FB_REGISTERED		= 9,
	WOE_REGISTER_FB_CANCEL_REG		= 10,
	WOE_REGISTER_FB_CANCEL_FAIL		= 11,
};

enum WOE_REJOIN_FB
{
	WOE_REJOIN_FB_FAILED			= 0,
	WOE_REJOIN_FB_NOTPOSSIBLE		= 1,
	WOE_REJOIN_FB_NOT_REGISTERED	= 2,
	WOE_REJOIN_FB_INVALID_CHARID	= 3,
	WOE_REJOIN_FB_INBATTLE			= 4,
};