#pragma once

enum EMNPC_ITEM_EXCHANGE_FB
{
	EMNPC_ITEM_EXCHANGE_FB_OK					= 0,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_NPC			= 1,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_ID			= 2,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_ITEM			= 3,
	EMNPC_ITEM_EXCHANGE_FB_NOCONTRIBUTIONPOINT	= 4,
	EMNPC_ITEM_EXCHANGE_FB_NOPOINT				= 5,
	EMNPC_ITEM_EXCHANGE_FB_NOT_INVEN_SPACE		= 6,
	EMNPC_ITEM_EXCHANGE_FB_REQUIRE_MISSING		= 7,
	EMNPC_ITEM_EXCHANGE_FB_DELETE_FAIL			= 8,
	EMNPC_ITEM_EXCHANGE_FB_INSERT_FAIL			= 9,
	EMNPC_ITEM_EXCHANGE_FB_INVALID_DATA			= 10,
	EMNPC_ITEM_EXCHANGE_FB_NO_PLAY_TIME			= 11,	/* play time system, Juver, 2021/01/27 */
	EMNPC_ITEM_EXCHANGE_FB_NOMONEY				= 12,	/* NpcExchange Gold Requirement | JX | 01-11-24*/
	EMNPC_ITEM_EXCHANGE_FB_NOCONTRI				= 13,	/* NpcExchange Contri Requirement | Jxyy | 11-21-24*/
};

enum RAN_PRODUCT_FB
{
	RAN_PRODUCT_FB_STARTED						= 0,
	RAN_PRODUCT_FB_INVALID_ID					= 1,
	RAN_PRODUCT_FB_INVALID_COST					= 2,
	RAN_PRODUCT_FB_INVALID_CHAR_LEVEL			= 3,
	RAN_PRODUCT_FB_RESULT_ITEM_INVALID			= 4,
	RAN_PRODUCT_FB_RESULT_ITEM_NO_SPACE			= 5,
	RAN_PRODUCT_FB_MATERIAL						= 6,
	RAN_PRODUCT_FB_FAIL_COSTUME					= 7,
	RAN_PRODUCT_FB_FAIL_DELETE					= 8,
	RAN_PRODUCT_FB_FAIL_INSERT					= 9,
	RAN_PRODUCT_FB_TASK_RUNNING					= 10,
	RAN_PRODUCT_FB_FEATURE_OFF					= 11,

	/* play time system, Juver, 2021/01/27 */
	RAN_PRODUCT_FB_INVALID_CHAR_PLAY_TIME		= 12,
	RAN_PRODUCT_FB_INVALID_CHAR_PLAY_POINT		= 13,
	RAN_PRODUCT_FB_INVALID_CHAR_CONTRI_POINT	= 14,
};

enum RAN_PRODUCT_PROCESS_FB
{
	RAN_PRODUCT_PROCESS_FB_OK					= 0,
	RAN_PRODUCT_PROCESS_FB_FAILED				= 1,
	RAN_PRODUCT_PROCESS_FB_FULL_INVEN			= 2,
	RAN_PRODUCT_PROCESS_FB_FAILED_INSERT		= 3,
};

/*rv card, Juver, 2017/11/25 */
enum EM_RANDOM_OPTION_CHANGE_FB
{
	EM_RANDOM_OPTION_CHANGE_INVALID_CARD_ITEM			= 0,
	EM_RANDOM_OPTION_CHANGE_INVALID_TARGET_ITEM			= 1,
	EM_RANDOM_OPTION_CHANGE_TARGET_NOT_SUIT				= 2,
	EM_RANDOM_OPTION_CHANGE_SUIT_MISMATCH				= 3,
	EM_RANDOM_OPTION_CHANGE_TARGET_OPTION_NOT_EXIST		= 4,
	EM_RANDOM_OPTION_CHANGE_TARGET_OPTION_ALREADY_SET	= 5,
	EM_RANDOM_OPTION_CHANGE_TARGET_OPTION_NOT_FREE		= 6,
	EM_RANDOM_OPTION_CHANGE_DONE_CHANGE					= 7,
	EM_RANDOM_OPTION_CHANGE_TARGET_INVALID				= 8,
};

/*nondrop card, Juver, 2017/11/26 */
enum EM_NONDROP_CARD_FB
{
	EM_NONDROP_CARD_INVALID_CARD_ITEM			= 0,
	EM_NONDROP_CARD_INVALID_TARGET_ITEM			= 1,
	EM_NONDROP_CARD_TARGET_NOT_SUIT				= 2,
	EM_NONDROP_CARD_TARGET_ALREADY				= 3,
	EM_NONDROP_CARD_DONE_CHANGE					= 4,
};

/* Add ItemShop, Ssodomain, 11-09-2023, Start */
enum EMREQ_ITEMSHOP_FROMDB_FB
{
	EMREQ_ITEMSHOP_FROMDB_FB_END		= 0,
	EMREQ_ITEMSHOP_FROMDB_FB_OK			= 1,
};
/* Add ItemShop, Ssodomain, 11-09-2023, End */

/*specific item box, Juver, 2018/09/03 */
enum EMREQ_ITEM_BOX_SPECIFIC
{
	EMREQ_ITEM_BOX_SPECIFIC_FAILED				= 0,
	EMREQ_ITEM_BOX_SPECIFIC_BAD_ITEM			= 1,
	EMREQ_ITEM_BOX_SPECIFIC_BAD_BOX				= 2,
	EMREQ_ITEM_BOX_SPECIFIC_BAD_CONTENTS		= 3,
	EMREQ_ITEM_BOX_SPECIFIC_BAD_SELECTED		= 4,
	EMREQ_ITEM_BOX_SPECIFIC_BAD_SELECTED_EXIST	= 5,
	EMREQ_ITEM_BOX_SPECIFIC_NO_INVEN_SPACE		= 6,
	EMREQ_ITEM_BOX_SPECIFIC_DONE				= 7,
};

/* set item option, Juver, 2021/09/04 */
enum EM_SET_OPTION_INSERT_FB
{
	EM_SET_OPTION_INSERT_FAILED					= 0,
	EM_SET_OPTION_INSERT_INVALID_TARGET_ITEM	= 1,
	EM_SET_OPTION_INSERT_INVALID_CARD_ITEM		= 2,
	EM_SET_OPTION_INSERT_TARGET_NOT_SUIT		= 3,
	EM_SET_OPTION_INSERT_TARGET_NOT_SET_OPTION	= 4,
	EM_SET_OPTION_INSERT_TARGET_ALREADY			= 5,
	EM_SET_OPTION_INSERT_DONE					= 6,
};

/* set item option, Juver, 2021/09/04 */
enum EM_SET_OPTION_REROLL_FB
{
	EM_SET_OPTION_REROLL_FAILED					= 0,
	EM_SET_OPTION_REROLL_INVALID_TARGET_ITEM	= 1,
	EM_SET_OPTION_REROLL_INVALID_CARD_ITEM		= 2,
	EM_SET_OPTION_REROLL_TARGET_NOT_SUIT		= 3,
	EM_SET_OPTION_REROLL_TARGET_NOT_SET_OPTION	= 4,
	EM_SET_OPTION_REROLL_DONE					= 5,
};

/*12-9-14, Battle Pass - CNDev*/
enum EMINVEN_REQ_BATTLEPASS_PREMIUM_CARD_FB
{
	EMINVEN_REQ_BATTLEPASS_PREMIUM_CARD_FAIL		= 0,
	EMINVEN_REQ_BATTLEPASS_PREMIUM_CARD_INVALID		= 1,
	EMINVEN_REQ_BATTLEPASS_PREMIUM_CARD_NOTCARD		= 2,
	EMINVEN_REQ_BATTLEPASS_PREMIUM_CARD_ALREADY		= 3,
	EMINVEN_REQ_BATTLEPASS_PREMIUM_CARD_SUCCESS		= 4,
};

enum EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_FB
{
	EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_FAIL		= 0,
	EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_INVALID		= 1,
	EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_NOTCARD		= 2,
	EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_NOTPREMIUM	= 3,
	EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_MAX			= 4,
	EMINVEN_REQ_BATTLEPASS_LEVELUP_CARD_SUCCESS		= 5,
};

/*12-9-14, Battle Pass - CNDev*/
enum EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_FB
{
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_FAIL		= 0,
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_NOTLEVEL	= 1,
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_NOTREWARD	= 2,
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_ALREADY		= 3,
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_NOTPREMIUM	= 4,
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_NOTINVEN	= 5,
	EMINVEN_REQ_BATTLEPASS_REWARD_CLAIM_SUCCESS		= 6,
};
/*12-16-24, daily login - CNDev*/
enum EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_FB
{
	EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_FAIL		= 0,
	EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_NOTDAY		= 1,
	EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_NOTREWARD	= 2,
	EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_ALREADY		= 3,
	EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_NOTINVEN	= 4,
	EMINVEN_REQ_DAILYLOGIN_REWARD_CLAIM_SUCCESS		= 5,
};