/*!
 * \file PVPClubDeathMatchDefine.h
 *
 * \author Juver
 * \date 2019/09/15
 *
 * 
 */

#ifndef PVPCLUBDEATHMATCHDEFINE_H_INCLUDED__
#define PVPCLUBDEATHMATCHDEFINE_H_INCLUDED__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define PVP_CLUB_DEATH_MATCH_CHAR_ID_NULL				0xFFFFFFFF	//similar to GAEAID_NULL
#define PVP_CLUB_DEATH_MATCH_CHAR_NAME_SIZE				33			//similar to CHAR_SZNAME

#define PVP_CLUB_DEATH_MATCH_CLUB_ID_NULL				0			//similar to CLUB_NULL
#define PVP_CLUB_DEATH_MATCH_CLUB_NAME_SIZE				33			//similar to CHAR_SZNAME

#define PVP_CLUB_DEATH_MATCH_SCHEDULE_NONE				UINT_MAX
#define PVP_CLUB_DEATH_MATCH_WINNER_NONE				UINT_MAX

#define PVP_CLUB_DEATH_MATCH_REG_NUM_BRD_TIME			5.0f		//time to broadcast members num
#define PVP_CLUB_DEATH_MATCH_PACKET_PLAYER_DATA_NUM		32			//agent to field player data
#define PVP_CLUB_DEATH_MATCH_PACKET_CLUB_DATA_NUM		22			//field to agent rank update

#define PVP_CLUB_DEATH_MATCH_REVIVE_TIME				10.0f		//revive time

#define PVP_CLUB_DEATH_MATCH_RANK_NONE					0xffff
#define PVP_CLUB_DEATH_MATCH_RANK_TOP					10

#define PVP_CLUB_DEATH_MATCH_PLAYER_HASH_SIZE			128			/* PVPClubDeathMatch hash check, Juver, 2021/07/18 */


enum PVP_CLUB_DEATH_MATCH_EVENT_STATE
{
	PVP_CLUB_DEATH_MATCH_EVENT_STATE_ENDED		= 0,
	PVP_CLUB_DEATH_MATCH_EVENT_STATE_REGISTER	= 1,
	PVP_CLUB_DEATH_MATCH_EVENT_STATE_BATTLE		= 2,
	PVP_CLUB_DEATH_MATCH_EVENT_STATE_REWARD		= 3,
	PVP_CLUB_DEATH_MATCH_EVENT_STATE_SIZE		= 4,
};


enum PVP_CLUB_DEATH_MATCH_SCHOOL
{
	PVP_CLUB_DEATH_MATCH_SCHOOL_SG		= 0,
	PVP_CLUB_DEATH_MATCH_SCHOOL_MP		= 1,
	PVP_CLUB_DEATH_MATCH_SCHOOL_PHX		= 2,
	PVP_CLUB_DEATH_MATCH_SCHOOL_SIZE	= 3,
};

namespace COMMENT
{
	extern std::string PVP_CLUB_DEATH_MATCH_EVENT_STATE[PVP_CLUB_DEATH_MATCH_EVENT_STATE_SIZE];
};

#endif // PVPCLUBDEATHMATCHDEFINE_H_INCLUDED__
