/*!
 * \file PVPClubDeathMatchControlMsgEnum.h
 *
 * \author Juver
 * \date 2020/11/10
 *
 * 
 */

#ifndef PVPCLUBDEATHMATCHCONTROLMSGENUM_H_INCLUDED__
#define PVPCLUBDEATHMATCHCONTROLMSGENUM_H_INCLUDED__

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

enum PVP_CLUB_DEATH_MATCH_REGISTER_FB
{
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_FAILED				= 0,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_INVALID_CHARID		= 1,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_NOTPOSSIBLE		= 2,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_INVALID_CHANNEL	= 3,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_LEVEL_LOW			= 4,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_INVALID_CLUB		= 5,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_CLUB_LEVEL_LOW		= 6,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_REQUIRE_RIGHTS		= 7,

	PVP_CLUB_DEATH_MATCH_REGISTER_FB_ALREADY_REG		= 8,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_FULL				= 9,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_REGISTERED			= 10,

	PVP_CLUB_DEATH_MATCH_REGISTER_FB_CANCEL_REG			= 11,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_CANCEL_FAIL		= 12,

	PVP_CLUB_DEATH_MATCH_REGISTER_FB_CANCEL_NOT_ENOUGH_MEMBERS	= 13,

	/* PVPClubDeathMatch hash check, Juver, 2021/07/18 */
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_DEVICE_INFO_ERROR	= 14,
	PVP_CLUB_DEATH_MATCH_REGISTER_FB_DEVICE_REGISTERED	= 15,
};

enum PVP_CLUB_DEATH_MATCH_REJOIN_FB
{
	PVP_CLUB_DEATH_MATCH_REJOIN_FB_FAILED				= 0,
	PVP_CLUB_DEATH_MATCH_REJOIN_FB_NOTPOSSIBLE			= 1,
	PVP_CLUB_DEATH_MATCH_REJOIN_FB_NOT_REGISTERED		= 2,
	PVP_CLUB_DEATH_MATCH_REJOIN_FB_INBATTLE				= 3,
};

#endif // PVPCLUBDEATHMATCHCONTROLMSGENUM_H_INCLUDED__
