//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EditorMapsList.rc
//
#define IDD_EDITORMAPSLIST_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_FILE_LOAD            1000
#define IDC_BUTTON_FILE_SAVE            1001
#define IDC_BUTTON_FILE_IMPORT          1002
#define IDC_BUTTON_MAPSLIST_ADD         1003
#define IDC_BUTTON_MAPSLIST_EDIT        1004
#define IDC_BUTTON_MAPSLIST_DELETE      1005
#define IDC_BUTTON_MAPSLIST_CLEAR       1006
#define IDC_BUTTON_MAPSLIST_SETFIELD_0  1007
#define IDC_BUTTON_MAPSLIST_COPY        1008
#define IDC_CHECK_MAP_USE               1009
#define IDC_EDIT_MAP_MID                1010
#define IDC_EDIT_MAP_SID                1011
#define IDC_EDIT_MAP_FIELD              1012
#define IDC_EDIT_MAP_NAME               1013
#define IDC_EDIT_MAP_LEVELFILE          1014
#define IDC_EDIT_MAP_BGM                1015
#define IDC_LIST_MAP                    1016
#define IDC_EDIT_MAP_LOADING            1017
#define IDC_CHECK_MAP_PEACEZONE         1018
#define IDC_CHECK_MAP_COMMISSION        1019
#define IDC_CHECK_MAP_PKZONE            1020
#define IDC_CHECK_MAP_FREEPK            1021
#define IDC_CHECK_MAP_ITEMDROP          1022
#define IDC_CHECK_MAP_MOVE              1023
#define IDC_CHECK_MAP_RESTART           1024
#define IDC_CHECK_MAP_PETACTIVITY       1025
#define IDC_CHECK_MAP_DECEXP            1026
#define IDC_CHECK_MAP_VEHICLEACTIVITY   1027
#define IDC_CHECK_MAP_CLUBBATTLEZONE    1028
#define IDC_CHECK_MAP_INSTANTMAP        1029
#define IDC_CHECK_MAP_QBOXENABLE        1030
#define IDC_BUTTON_MAP_SAVE             1031
#define IDC_BUTTON_MAP_LEVELFILE        1032
#define IDC_BUTTON_MAP_BGMFILE          1033
#define IDC_BUTTON_MAP_LOADINGIMAGE     1034
#define IDC_CHECK_MAP_LUNCHBOXFORBID    1035
#define IDC_CHECK_MAP_CPRESET           1036
#define IDC_CHECK_MAP_PKMAP             1037
#define IDC_CHECK_MAP_UI_MAP_SELECT     1038
#define IDC_CHECK_MAP_UI_MAP_INFO       1039
#define IDC_CHECK_MAP_CLUB_PK_RECORD    1040
#define IDC_CHECK_MAP_OPEN_PRIVATE_MARKET 1041
#define IDC_CHECK_MAP_PARTY_SPARRING    1042
#define IDC_CHECK_MAP_BLOCK_TAXI        1043
#define IDC_CHECK_MAP_BLOCK_FRIENDCARD  1044
#define IDC_CHECK_MAP_BLOCK_RECALL      1045
#define IDC_CHECK_MAP_BLOCK_TELEPORT    1046
#define IDC_CHECK_MAP_DISABLE_SYSTEM_BUFFS 1047
#define IDC_CHECK_MAP_BLOCK_HPPOTION    1048
#define IDC_CHECK_MAP_BLOCK_PARTY       1049
#define IDC_CHECK_MAP_FORCE_REVIVE      1050
#define IDC_BUTTON_MAPSLIST_CREATE_LIST 1051
#define IDC_CHECK_MAP_OPEN_PK           1052
#define IDC_CHECK_MAP_DEATH_HIDE        1053
#define IDC_CHECK_MAP_USER_VERIFIED_MAP_ENTRY 1054
#define IDC_BUTTON_CREATE_FROM_LUA      1055
#define IDC_CHECK_COSTUME_COMBINE_RESTRICT_MOVESPEED 1056
#define IDC_CHECK_COSTUME_COMBINE_RESTRICT_ATTACKSPEED 1057
#define IDC_CHECK_MAP_TRADE_RESTRICTED  1058
#define IDC_BUTTON_CSV_LOAD             1059
#define IDC_BUTTON_CSV_SAVE             1060
#define IDC_CHECK_MAP_ALLOW_HIDE_DEAD   1061
#define IDC_CHECK_MAP_SHOW_PK_MARK      1062
#define IDC_CHECK_MAP_USE_AUTO_POTION   1063
#define IDC_CHECK_MAP_USE_AUTO_PILOT    1064
#define IDC_CHECK_MAP_PK_MAP_COUNT      1065
#define IDC_CHECK_MAP_CPRESET_DEATH     1066
#define IDC_CHECK_MAP_USE_CAPTCHA       1067
#define IDC_CHECK_MAP_AUTO_POTION_MANUAL 1068
#define IDC_CHECK_MAP_DISABLE_GENERAL_CHAT 1069
#define IDC_CHECK_MAP_USE_AUTO_PILOT2   1070
#define IDC_CHECK_MAP_RESET_SKILL_WHENDIE 1070
#define IDC_CHECK_MAP_BOSS_TRACKER      1071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
